// constants.ts
// Centralized JSON constants
// ------------------------------------------------------------
// Add new JSON blocks as exported constants in this file.
// Each block should be valid JSON (keys/values), typed via JSONValue/JSONObject below.
// Example:
// export const HOME_PAGE_COPY: JSONObject = {
//   title: "Welcome",
//   hero: { headline: "Acme", subtitle: "Do more" },
// };

// Generic JSON types
export type JSONValue = string | number | boolean | null | JSONValue[] | { [key: string]: JSONValue };
export type JSONObject = { [key: string]: JSONValue };

export type StarKey =
  | "紫微" | "破军" | "天府" | "廉贞" | "太阴" | "贪狼" | "巨门" | "天同"
  | "天相" | "武曲" | "天梁" | "太阳" | "七杀" | "天机" | "左辅" | "右弼" | "文昌" | "文曲";
// ------------------------------------------------------------
// 🔽 Add your exported JSON blocks below this line
// ------------------------------------------------------------

export const EXECUTION_STYLE_DESCRIPTION: JSONObject = {
  "Commander": "You operate as a Commander: crisp decisions, visible cadence, zero drift. You convert strategy into sprints, set check-in rhythms, and make ownership unambiguous. Colleagues read your scoreboard and understand what ‘done’ means, because you define acceptance criteria and close loops fast. You tend to decide early, narrow scope, and protect momentum under pressure. This discipline delivers results, especially in deadline-heavy work. Watchouts: bulldozing discovery or muting dissent. Build a short ‘challenge the plan’ window, run quick pre-mortems, and calibrate risk before locking the route. You lead best where pace, structure, and accountability matter.",
  "Architect": "You operate as an Architect: measured, exacting, clarity-first. You design systems before speed, mapping flows, interfaces, and failure modes so teams build once, not twice. Documentation, quality gates, and versioned standards are your leverage; you prevent rework and create scale. You tend to front-load discovery, test assumptions early, and make trade-offs explicit. This steadiness suits regulated, complex, or long-horizon work. Watchouts: slow starts and analysis drag. Timebox investigation, define ‘good enough’ thresholds, prototype to de-risk, and set decision windows so progress compounds while quality stays high.",
  "Catalyst": "You operate as a Catalyst: fast, flexible, momentum-hungry. You spark experiments, recruit allies, and turn small wins into a narrative that moves people. You prefer shipping a scrappy v1, gathering live signal, and iterating in tight loops. You tend to unblock with influence, connect dots across teams, and keep energy high when others stall. This bias accelerates launches and change initiatives. Watchouts: inconsistency, mess, and unmanaged exposure. Add simple guardrails—budgets, stop-rules, owners—so bets stay contained. Broadcast learning openly and codify what works so sparks become repeatable systems.",
  "Integrator": "You operate as an Integrator: collaborative, adaptive, steady under complexity. You connect contexts, translate aims between functions, and shape shared routines that let diverse people do great work together. Discovery and co-design are your starting moves; you surface dissent early and help the group decide well. You tend to resolve friction, negotiate interfaces, and sustain progress through rituals and follow-through. This style shines in cross-silo programs and partnership-heavy work. Watchouts: soft boundaries and slow decisions. Define authority, escalation paths, and decision windows upfront so harmony does not dilute accountability."
};

export const EXECUTION_STYLE_LEADERSHIP: JSONObject = {
  "Commander": "Lead with cadence and clarity. Set weekly targets, daily signals, and a visible scoreboard. Define 'done' with acceptance criteria, owners, and SLA-like timelines. Protect deep-work blocks, triage scope, and remove blockers quickly. Invite dissent before committing; run pre-mortems on critical bets. Your edge: speed with discipline—use guardrails, not micromanagement, to keep pace high and quality reliable.",
  "Architect": "Lead by design and documentation. Start with a written architecture brief, interfaces, and service levels. Establish stage gates, review checklists, and test thresholds before spend scales. Timebox discovery, prototype risky components, and publish decision logs people can trust. Coach teams to write, version, and refactor their standards. Your edge: reliability at scale—systems that make good choices the default.",
  "Catalyst": "Lead through momentum and narrative. Frame bets with clear success criteria, budgets, and stop rules. Launch scrappy pilots, broadcast learning, and promote owners who move first responsibly. Keep cycles short, celebrate progress, and make it safe to sunset losing ideas. Pair speed with lightweight risk caps and a simple escalation path. Your edge: energy that converts possibilities into adoption.",
  "Integrator": "Lead through alignment and boundaries. Facilitate kickoffs that clarify roles, decision rights, and interfaces. Install rituals—standups, demos, retros—that surface dissent and commitments. Map dependencies, negotiate SLAs across teams, and keep a shared roadmap visible. Set decision windows and escalation paths so harmony doesn't slow action. Your edge: durable collaboration that turns complexity into coordinated execution."
};

export const EXECUTION_STYLE_TEAM_MEMBER: JSONObject = {
  "Commander": "Contribute with ownership and speed. Take clear slices of scope, define ‘done,’ and post daily signals so others can align. Unblock yourself quickly, escalate with options, and close loops in writing. Invite dissent before finalizing, and use lightweight checklists to keep quality high without slowing cadence.",
  "Architect": "Contribute through rigor and clarity. Write short specs, document interfaces, and keep runbooks current so teammates move confidently. Raise risks early with data, propose prototypes to test assumptions, and follow stage gates without ceremony. Protect quality by using checklists and peer review while keeping decisions timeboxed.",
  "Catalyst": "Contribute by creating momentum. Volunteer for ambiguous work, ship a scrappy v1, and broadcast learning so the team sees signal quickly. Recruit allies, keep cycles short, and manage exposure with budgets and stop rules. Turn wins into repeatable plays by codifying what worked after each iteration.",
  "Integrator": "Contribute by connecting dots. Translate between functions, map dependencies, and track agreements so handoffs are smooth. Surface dissent early and help the group decide within clear windows. Hold boundaries kindly—clarify ownership, document next steps, and follow through until commitments are closed."
};

export const EXECUTION_STYLE_LEVERAGE: JSONObject = {
  "Commander": [
    {
      "title": "Cadence",
      "description": "Install weekly goals, daily progress signals, and a single visible scoreboard. Name owners, due dates, and dependencies. Keep work in small, inspectable increments so speed is measurable and slippage is obvious."
    },
    {
      "title": "Process",
      "description": "Codify your playbooks: definitions of done, SOPs, and handoff checklists. Write once, reuse often, and tighten after each retro. Documentation should make the next person faster without you in the room."
    },
    {
      "title": "Accountability",
      "description": "Run a short dissent window, then commit. Log decisions, run pre‑mortems on critical bets, and cap scope changes with a simple change request. Remove blockers same day and close loops in writing to reinforce standards."
    }
  ],
  "Architect": [
    {
      "title": "System Design",
      "description": "Start with an architecture brief: objectives, constraints, interfaces, and failure modes. Map data and control flows, choose standards, and draw boundaries. Aim for maintainability and clear ownership before a line of code ships."
    },
    {
      "title": "Documentation",
      "description": "Create living specs, templates, and runbooks. Version them, link to decisions, and automate check generation where possible. Good docs make onboarding trivial and reduce meetings."
    },
    {
      "title": "Quality Gates",
      "description": "Define review criteria, test thresholds, and rollout stages. Instrument quality metrics and make them visible. Ship behind feature flags and learn safely before broad release."
    }
  ],
  "Catalyst": [
    {
      "title": "Small Bets",
      "description": "Frame bets with success criteria, budget, and stop‑rules. Ship a scrappy v1 in days, not weeks, and capture real‑world signal. Use the data to double‑down or sunset quickly."
    },
    {
      "title": "Narrative Power",
      "description": "Tell the story: problem, bet, signal, next move. Demo early, recruit early adopters, and broadcast wins and lessons. Momentum compounds when people can see progress."
    },
    {
      "title": "Guardrails",
      "description": "Keep exposure contained: cap spend, limit blast radius, and assign a single owner. Maintain a simple risk log and a 24‑hour escalation path. Speed is safe when the edges are clear."
    }
  ],
  "Integrator": [
    {
      "title": "Alignment",
      "description": "Open with a kickoff that sets shared goals, roles, and working norms. Use one roadmap and transparent priorities. Facilitate to surface dissent fast and commit as a group."
    },
    {
      "title": "Interfaces",
      "description": "Map dependencies and agree on SLAs, definitions, and integration checkpoints. Create checklists for handoffs and a shared glossary to reduce rework across functions."
    },
    {
      "title": "Decision Hygiene",
      "description": "Timebox choices, define decision rights, and document outcomes with owners. Escalate on facts, not politics, and run regular retros to refine the collaboration system."
    }
  ]
};


// Life Palace descriptions for selected Zi Wei Dou Shu stars
// Keys are Chinese star names; copy is business-ready and practical.

export const STAR_LIFE_MEANINGS: Partial<Record<StarKey, string>> = {
  "紫微": "When this star is in the Life Palace, you carry calm authority, long‑range vision, and a duty‑of‑care mindset. People look to you for standards and steadiness under pressure. Your best work sets direction, formalizes ownership, and installs systems that outlast you. Risks include over‑control, pride, or taking everything on yourself. Delegate real authority, write decision logs, and measure outcomes rather than hours so influence scales without bottlenecking at you.",
  "破军": "This placement signals reinvention: you dismantle what no longer serves and rebuild better scaffolding. You move fast in turnarounds, restructures, or new markets, pairing courage with focus. Strengths are sharp calls and willingness to start again. Risks include chaos, sunk‑cost denial, or breaking faster than you rebuild. Use phased plans, clear kill criteria, and owner handoffs so change is bold yet controlled—and the new stabilizes quickly.",
  "天府": "This placement emphasizes resource stewardship, logistics, and quiet reliability. You maintain buffers, vendor trust, and operating rhythm so teams deliver even in rough weather. People experience you as fair and dependable. Shadow patterns include hoarding, slow pivots, or cushioning others from necessary reality. Share dashboards, define triggers for reallocating capital, and rotate ownership to prevent bottlenecks. Your brand is stability that compounds into durable advantage.",
  "廉贞": "Here the theme is principled reform and credible boundaries. You challenge fuzzy standards, write clearer ones, and protect brand and culture when incentives tilt the wrong way. This excels in governance, policy, audits, or negotiations. Watch for combative framing or change for its own sake. Anchor to written principles, define non‑negotiables, and measure behavior change. Strong boundaries turn passion into leverage, not politics.",
  "太阴": "This placement brings craft, reflection, and deep listening. You notice nuance, elevate quality, and protect focus for yourself and others. Your output ages well because it’s thoughtful and considerate. Risks include perfectionism, mood‑based decisions, or delaying action while polishing. Use checklists, peer review, and time‑boxed drafts to ship steadily. Roles in design, research, editorial, or advisory work reward patient precision.",
  "贪狼": "Expect appetite, charm, and deal‑making. You open doors, spot optionality, and convert relationships into opportunities. This shines in sales, partnerships, entertainment, and innovation labs. Risks include distraction, over‑promising, or risk taken for excitement rather than strategy. Set qualification rules, maintain a clean pipeline, and align bets to north‑star metrics. When desire is focused, magnetism becomes a reliable growth engine.",
  "巨门": "This placement sharpens questioning, negotiation, and signal‑seeking. You surface what’s unsaid, pressure‑test narratives, and protect teams from hidden risk. Powerful in discovery, due diligence, and communications. The shadow is cynicism or paralysis through critique. Pair probing with proposal—whenever you raise a concern, offer options and trade‑offs. Your voice creates clarity when it also points to actionable paths forward.",
  "天同": "Expect calm empathy, service, and protective routines. You build environments where people do consistent, healthy work and clients feel looked after. Strength is steadiness—care that shows up on time and keeps promises. Risks include comfort‑seeking, conflict avoidance, or staying under‑challenged. Use clear boundaries, simple SLAs, and incremental goals to keep growth gentle but real. Client success and people leadership fit well.",
  "天相": "Here the signature is diplomacy, integrity, and partnership stewardship. You design fair processes, mediate conflict, and help groups decide well. Colleagues trust your judgment when stakes cross functions or organizations. Risks include people‑pleasing, slow choices, or smoothing over hard truths. Define decision rights early, summarize agreements in writing, and set escalation paths. An even hand turns complex collaborations into workable agreements.",
  "武曲": "This placement emphasizes discipline, asset control, and operational certainty. You build durable value through budgets, controls, and performance metrics. Teams rely on your toughness under pressure and refusal to let standards slip. Risks include rigidity or blocking bold moves when warranted. Pair financial spine with pragmatic experiments and post‑mortems. In finance, procurement, or scaled operations, reliability becomes a competitive edge.",
  "天梁": "You show up as mentor, protector, and ethical backstop. You safeguard standards, coach calmly, and make prudent calls when others panic. Strength is mature perspective that reduces unforced errors. Watch for paternalism or rescuing work that should be owned by others. Empower, don’t over‑shelter; set boundaries and make capability‑building part of the plan. Oversight, risk, and advisory roles benefit from this presence.",
  "太阳": "This placement brings visible service, optimism, and energizing leadership. You illuminate problems, share credit, and rally people around mission. Your presence raises standards and morale in public‑facing work. Risks include overcommitment or performing leadership instead of practicing it. Protect energy with boundaries, delegate execution, and let results—not spotlight—prove value. Education, outreach, and customer‑centric roles let influence scale.",
  "七杀": "Decisive, bold, and turnaround‑oriented energy is present. You cut through noise, take responsibility, and act when others stall—vital in crises or competitive pushes. Risks include volatility, unnecessary conflict, or burning bridges. Install guardrails: pre‑mortems, clear rules of engagement, and staged exposure. When channeled, courage accelerates necessary change without collateral damage.",
  "天机": "This marks you as strategist and pattern‑finder. You map systems, test assumptions, and pivot cleanly when the model changes. People rely on your curiosity and scenario planning. Risks include analysis loops, shifting priorities, or anxious over‑tuning. Use timeboxed research, small experiments, and clear decision windows to convert insight into movement. Strategy, product, and operations design suit this signature.",
  "左辅": "Enablement and steady support define this placement. You make others effective—clearing paths, supplying tools, and closing loops. Teams rely on your reliability and readiness to help. Risks include over‑functioning or becoming a quiet bottleneck. Build scalable templates, teach what you do, and rotate ownership. Influence grows when assistance becomes an operating system, not personal heroics.",
  "右弼": "Expect partnership and constructive companionship. You sync quickly with leaders, translate goals into tasks, and keep momentum humane. Watch for rescuing weak process or shielding avoidable mistakes. Ask for clear decision rights, keep written agreements, and escalate early when alignment slips. In strong systems, collaborative discipline multiplies impact.",
  "文昌": "This placement points to intellect, learning, and eloquence. In the Life Palace it highlights clarity of thought, synthesis, and a talent for structured communication. You excel at articulating ideas, documenting decisions, and teaching. Risks include overthinking, indecision, or staying theoretical. Convert insight into action with outlines, drafts, and shipping schedules. Pair analysis with delivery so your voice becomes a lever for influence.",
  "文曲": "Here the tone is artistry, persuasion, and taste. You frame ideas beautifully, translate emotion into language, and create work that resonates. This helps in branding, storytelling, and client relations. Risks include sentiment over substance or polishing without testing. Ground craft with clear briefs, audience data, and review checkpoints. When form meets evidence, the message moves markets rather than moods."
};

// Career Palace (官禄) descriptions for selected Zi Wei Dou Shu stars
// Keys are Chinese star names; descriptions are English-only and practical.

export const STAR_CAREER_MEANINGS: Partial<Record<StarKey, string>> = {
  "紫微": "In the Career Palace, this placement signals executive presence and stewardship. You set direction, codify standards, and keep teams steady through change. Your edge is calm judgment under pressure and the ability to align stakeholders around a clear roadmap. Risks: centralizing decisions, slow delegation, or protecting legacy structures too long. Lead by publishing priorities, assigning decision rights, and building successors. Track outcomes, not activity, and let governance, ethics, and long-horizon strategy showcase your value.",
  "破军": "In the Career Palace, this point favors transformation work—turnarounds, restructures, new markets. You excel at decisive calls, clearing blocked paths, and rebuilding systems fast. Your momentum is an asset when the mandate is change. Risks: unmanaged chaos, team whiplash, or breaking faster than you stabilize. Use staged rollouts, pre‑agreed kill criteria, and tight owner handoffs. Pair bold moves with a stabilization plan so the new operating model takes root.",
  "天府": "Here the signature is resource stewardship and operational reliability. You safeguard budgets, vendors, and buffers so delivery is predictable. Teams trust you to keep the machine running and risks contained. Risks: excess caution, inventory that ties up capital, or shielding failing bets. Instrument leading indicators, define triggers for reallocation, and run quarterly resilience reviews. Roles in operations, finance, and supply chain spotlight your steady compounding.",
  "廉贞": "In the Career Palace, this star leans toward governance, policy, and principled negotiation. You design fair rules, protect brand integrity, and keep incentives clean. You are effective in compliance-heavy industries and high-stakes deals. Risks: combative tone, politicized battles, or change for its own sake. Convert values into written standards, publish decision logs, and measure behavior shifts. Clear non‑negotiables plus transparent processes turn conviction into credible power.",
  "太阴": "Here the emphasis is craft, care, and thoughtful execution. You raise quality, protect focus, and design environments where good work repeats. Strong fit with research, design, education, and advisory careers. Risks: perfectionism, invisibility, or delaying decisions while polishing. Use acceptance criteria, time‑boxed drafts, and peer review to keep shipping. Your quiet standards build reputation capital that compounds with each release.",
  "贪狼": "In the Career Palace, this placement favors growth engines—sales, partnerships, business development, entertainment. You open doors, shape offers, and turn relationships into revenue. Your energy builds pipelines and expands optionality. Risks: shiny‑object drift, over‑promising, or betting for excitement rather than strategy. Install qualification rules, stage gates, and forecast hygiene. When appetite is focused, you become a dependable driver of new business.",
  "巨门": "Here the power is in inquiry, advocacy, and narrative control. You surface hidden issues, negotiate terms, and keep decisions honest. Strong fit with communications, policy, legal, research, and product discovery. Risks: reputation for negativity or analysis that stalls momentum. Pair every critique with options and trade‑offs. Create issue logs, decision memos, and structured debates so your questions accelerate clarity instead of slowing it.",
  "天同": "In the Career Palace, this star supports service systems and humane operations. You design repeatable client experiences, protect employee wellbeing, and make reliability visible. Great for HR, customer success, care delivery, and community roles. Risks: conflict avoidance, staying too comfortable, or absorbing work without boundaries. Use SLAs, clear queues, and escalation paths. Your steady care becomes a scalable service when it’s systemized.",
  "天相": "This placement favors diplomacy, cross‑functional leadership, and partnership stewardship. You convene, mediate, and guide groups to workable decisions. Ideal for program management, key accounts, alliances, and public affairs. Risks: slow choices or smoothing hard truths. Define decision rights early, write agreements, and set decision windows. With transparent rules, your even hand turns complexity into coordinated execution.",
  "武曲": "In the Career Palace, this star anchors discipline—finance, controls, and performance engineering. You build budgets, dashboards, and thresholds that keep output dependable. Teams count on your toughness and refusal to let standards slip. Risks: rigidity, blocking necessary bets, or mistaking control for progress. Balance controls with small, instrumented trials and post‑mortems. Your best roles blend fiscal spine with pragmatic improvement loops.",
  "天梁": "Here the theme is oversight, ethics, and protective leadership. You mentor calmly, define floors that cannot be breached, and prevent unforced errors. Valuable in risk, audit, safety, and advisory tracks. Risks: paternalism or rescuing ownership. Coach capability, not dependency; publish guardrails and consequences. When accountability is clear, your protective stance increases trust without slowing action.",
  "太阳": "In the Career Palace, this placement amplifies visibility, service, and morale leadership. You energize teams, communicate clearly, and raise standards in public‑facing work. Strong in sales leadership, education, PR, and customer operations. Risks: burnout, busyness theater, or chasing spotlight over substance. Protect capacity with boundaries and delegate execution. Let consistently delivered results—not stage time—prove value.",
  "七杀": "Here the profile is surgical action under pressure. You thrive in crises, competitive pushes, and zero‑to‑one launches. You cut through noise, assume responsibility, and move the ball when others hesitate. Risks: collateral conflict, volatility, or scorched‑earth wins. Install rules of engagement, run pre‑mortems, and stage exposure. When aimed well, your decisiveness turns inflection points into progress without unnecessary fallout.",
  "天机": "In the Career Palace, this star favors strategy, systems thinking, and adaptive planning. You model scenarios, test assumptions, and adjust course with evidence. Great for product management, operations design, and analytics‑driven roles. Risks: analysis loops, shifting priorities, or nervous tinkering. Timebox discovery, pre‑define decision criteria, and move to experiments quickly. Your curiosity creates value when it ships as learnings and better playbooks.",
  "左辅": "Here the leverage is enablement and execution support. You make leaders and teams more effective by clearing paths, standardizing tools, and keeping loops closed. Excellent as chief‑of‑staff, PMO, or platform ops. Risks: over‑functioning or quietly hoarding institutional knowledge. Build templates, teach what you systemize, and rotate ownership. Scaled enablement—not personal heroics—becomes your brand.",
  "右弼": "In the Career Palace, this star focuses on partnership execution and humane coordination. You translate goals into workable plans, maintain alignment, and smooth handoffs. Strong for project leadership, account delivery, and operations liaison roles. Risks: rescuing weak process or shielding avoidable mistakes. Ask for clear decision rights, keep written agreements, and escalate early. Your steady collaboration multiplies impact in well‑run systems.",
  "文昌": "Here the emphasis is structured thinking and clear communication. You synthesize information, document decisions, and teach through writing. Great for analysis, knowledge management, product ops, and editorial leadership. Risks: overthinking, indecision, or staying in theory. Work in drafts, set publishing cadences, and tie content to actions. When ideas ship as playbooks, your clarity scales across the organization.",
  "文曲": "In the Career Palace, this star elevates brand, persuasion, and aesthetic judgment. You craft stories that move clients and align teams. Strong in marketing, design, sales enablement, and executive communications. Risks: polish over substance or creating without testing. Use clear briefs, audience data, and review checkpoints. When craft is evidence‑led, your voice doesn’t just sound good—it changes behavior."
};

// Wealth Palace (财帛) descriptions for selected Zi Wei Dou Shu stars
// Keys are Chinese star names; descriptions are English-only and practical.

export const STAR_WEALTH_MEANINGS: Partial<Record<StarKey, string>> = {
  "紫微": "In the Wealth Palace, this placement favors stewardship and capital policy. You allocate with a long horizon, set clear rules for spending vs. investment, and build trust that compounds. Strengths include portfolio governance and measured risk budgets. Risks: centralizing every decision or defending legacy assets too long. Publish an allocation rubric, delegate thresholds, and track return on invested time as well as money so resources move toward the mission, not status.",
  "破军": "Here the theme is reinvention of capital. You excel at pruning underperformers, exiting sunk costs, and redeploying into higher‑yield opportunities. Distressed assets, turnarounds, and ‘clean slate’ bets can suit you. Risks: churn, rebuild fatigue, or volatility that erodes confidence. Use position sizing, staged entry/exit rules, and written kill criteria. Pair bold reallocations with stabilization milestones so wealth grows after the break, not just during it.",
  "天府": "This placement leans toward preservation, reserves, and predictable cashflow. You manage buffers, vendor terms, and recurring income so compounding can work. Strengths include budgeting, treasury, and contingency planning. Risks: hoarding capital, slow pivots, or cushioning failing bets. Set rebalancing cadences, define drawdown triggers, and publish a simple liquidity ladder. Patient instruments and reliable operations become your edge.",
  "廉贞": "Wealth here is protected by standards and clean negotiations. You defend pricing integrity, codify terms, and prevent value leakage in contracts and compliance. Strong in regulated industries and brand‑sensitive deals. Risks: rigidity, needless battles, or rules that outlive their purpose. Translate principles into operating clauses, track concessions, and link incentives to desired outcomes. Clear boundaries turn values into margin instead of friction.",
  "太阴": "This placement favors patient accumulation and quality‑led earnings. Advisory, craftsmanship, royalties, and retainers fit well. You grow by deepening expertise, protecting focus, and delivering work that ages well. Risks: undercharging, perfection delays, or invisible impact. Set pricing floors, offer retainers, and ship on a cadence. When care meets consistency, your reputation compounds into steady income and durable referrals.",
  "贪狼": "Expect growth via deal flow and optionality. Partnerships, new offers, cross‑sells, and audience monetization can expand revenue lines. Your energy opens doors and creates multiple streams. Risks: overextension, shiny‑object spend, or promises outrunning delivery. Install qualification rules, keep a clean pipeline, and tie bets to north‑star metrics. With appetite aimed, charm converts to dependable top‑line gains.",
  "巨门": "Wealth here is built through inquiry and disciplined pricing. You excel at due diligence, pressure‑testing assumptions, and negotiating value rather than discounts. Strengths: forensic analysis and narrative control in deals. Risks: paralysis through critique or a reputation for saying no. Pair every challenge with options and a clear path to yes. Your skepticism protects margin when it also proposes workable terms.",
  "天同": "This placement rewards service models that emphasize retention. Memberships, subscriptions, and long‑term care accounts respond to your steadiness. You grow by keeping promises and smoothing client effort. Risks: over‑giving, weak boundaries, or underpricing. Use SLAs, tiered packages, and renewal rituals. Measure lifetime value, not just new logos—your compounding comes from staying power.",
  "天相": "Here wealth comes from fair partnerships and balanced trade. You broker alliances, structure revenue shares, and maintain trust across parties. Ideal for joint ventures, key accounts, and ecosystem plays. Risks: people‑pleasing, slow escalations, or ambiguous splits. Define decision rights and economics up front, summarize agreements in writing, and review performance on a cadence. Consistent governance turns diplomacy into durable income.",
  "武曲": "This placement centers on margins, controls, and unit economics. You build budgets, dashboards, and thresholds that keep cash conversion healthy. Strengths: cost discipline and performance engineering. Risks: penny‑wise choices that starve growth, or control mistaken for progress. Invest in productivity levers, run small instrumented trials, and enforce post‑mortems. When discipline funds smart bets, margin and momentum rise together.",
  "天梁": "Expect protective wealth practices: risk transfer, safeguards, and ethical screens. You reduce unforced losses through insurance, compliance hygiene, and vendor due diligence. Strengths include mentoring others on prudent choices. Risks: over‑insuring, excessive caution, or rescuing spend that should be cut. Define floors that cannot be breached, document contingencies, and educate stakeholders. Protection becomes a platform for confident growth.",
  "太阳": "Here wealth is tied to visibility, education, and public value. You monetize through content, events, teaching, and leadership that attracts opportunity. Strengths: audience trust and morale‑lifting brand. Risks: vanity metrics, burnout, or chasing spotlight over conversion. Design funnels, set conversion targets, and protect capacity with boundaries. When service meets signal, reputation turns into revenue reliably.",
  "七杀": "This profile favors tactical, high‑conviction bets—crisis arbitrage, competitive pushes, and bold entries. You act when others hesitate and can capture dislocated value. Risks: collateral damage, volatility, or concentration risk. Use position sizing, stop rules, and pre‑mortems. Stage exposure and secure downside floors. Aimed well, decisiveness converts inflection points into outsized gains without burning the portfolio.",
  "天机": "Here wealth is research‑driven and iterative. You write theses, run small tests, and adjust allocation with evidence. Strengths: systems thinking and continuous improvement. Risks: constant tweaking, whiplash pivots, or analysis that delays compounding. Pre‑define decision criteria, limit changes per cycle, and review outcomes in writing. When curiosity ships as disciplined playbooks, returns improve steadily.",
  "左辅": "Wealth grows through enablement and scalable tooling. You create templates, platforms, or shared services that others pay for—or that expand internal margin. Strengths: making teams efficient and monetizing repeatability. Risks: being the unpaid helper or hoarding know‑how. Productize what you build, set internal chargebacks or pricing, and rotate ownership. Enablement at scale becomes an asset on the balance sheet.",
  "右弼": "This placement monetizes collaboration—co‑selling, alliances, referrals, and partner‑led expansion. You translate goals into joint plans and keep commercial handoffs smooth. Risks: subsidizing weak partners or absorbing scope creep. Use written scopes, revenue‑share rules, and early escalation paths. When coordination is crisp, partnership revenue becomes predictable instead of accidental.",
  "文昌": "Here wealth is knowledge‑led. You synthesize, document, and teach—turning expertise into courses, playbooks, and advisory retainers. Strengths: clarity, writing, and content that scales. Risks: over‑editing, theory without delivery, or shipping too slowly. Work in drafts, publish on a cadence, and tie content to offers. When ideas become products, your insight compounds into recurring income.",
  "文曲": "This placement monetizes taste and persuasion. Brand strategy, design IP, storytelling, and premium positioning turn aesthetic judgment into pricing power. Risks: polish over substance or creating without testing. Use briefs, audience data, and A/B validation. Package assets for licensing and protect rights. When craft is evidence‑led, brand equity becomes an appreciating asset rather than a cost."
};
