/**
 * Zi Wei Dou Shu meanings as a single lookup object.
 * Keys:
 *  - Cycle (12 Decade Palaces): "大命","大兄","大夫","大子","大财","大疾","大迁","大友","大官","大田","大福","大父"
 *  - Star (18 primaries): "紫微","破军","天府","廉贞","太阴","贪狼","巨门","天同","天相","武曲","天梁","太阳","七杀","天机","左辅","右弼","文昌","文曲"
 *
 * The current file includes fully-populated text for 大命 and 大兄.
 * Other cycles are placeholders you can fill progressively.
 */

export type StarKey =
  | "紫微"
  | "破军"
  | "天府"
  | "廉贞"
  | "太阴"
  | "贪狼"
  | "巨门"
  | "天同"
  | "天相"
  | "武曲"
  | "天梁"
  | "太阳"
  | "七杀"
  | "天机"
  | "左辅"
  | "右弼"
  | "文昌"
  | "文曲";

export type CycleKey =
  | "大命"
  | "大兄"
  | "大夫"
  | "大子"
  | "大财"
  | "大疾"
  | "大迁"
  | "大友"
  | "大官"
  | "大田"
  | "大福"
  | "大父";

/**
 * Single JSON-like lookup: Cycle -> Star -> Meaning
 * Using Partial<Record<StarKey, string>> so incomplete cycles are valid.
 */
export const DECADE_CYCLE_MEANINGS: Record<
  CycleKey,
  Partial<Record<StarKey, string>>
> = {
  大命: {
    紫微: "This 10-year chapter casts you as the organizer-in-chief—standards, vision, and calm judgment become your signature. Treat it as an institution-building arc: publish a roadmap, set meeting cadences, and delegate real authority so results don’t bottleneck at you. If status or ego muddies choices, ask, “Which outcome matters most right now?” then decide. Build two successors and a written playbook so your impact scales beyond your presence.",
    破军: "Through this decade, reinvention is the point: creative destruction clears space for better systems. Run fast experiments with pre-agreed kill criteria; if a test fails twice, shut it down within a week and reassign resources. Do a pre-mortem before big moves and keep two fallback paths ready—bold doesn’t have to mean reckless. Cut cleanly, then rebuild scaffolding so the new can grow quickly.",
    天府: "Over the current cycle, consolidation and steady compounding beat flashy spikes. Prioritize buffers, airtight ops, and patient investments you can actually hold; reliability becomes your brand. Each quarter, audit cashflow and risk, and set “floor + stretch” targets to balance safety with ambition. Say yes to durability, no to drift—trust and reserves open quiet doors.",
    廉贞: "Right now, disciplined desire and credible boundaries turn into leverage. Convert values into written standards, protect your brand, and channel passion into structured achievements and clean negotiations. When politics get sticky, move to documented terms and time-boxed decisions. Three non-negotiables plus one arena for play keep you powerful without getting trapped.",
    太阴: "Across this 10-year phase, soft power does the heavy lifting—design, research, and patient finance compound in the background. Schedule deep-work blocks, automate savings, and let small improvements stack. If hesitation stalls you, ship a modest version within 48 hours and iterate calmly. Quiet craft plus money hygiene turns subtle moves into durable gains.",
    贪狼: "During this decade, magnetism and audience energy are high—partnerships, campaigns, and lifestyle ventures respond. Pair every splash (launch, event, promo) with a back-end plan (ops, budgets, fulfillment) so momentum stays healthy. Standardize boundaries to avoid entanglements, and track one metric that proves the charm works—conversion, retention, or revenue. Keep the sparkle; add discipline.",
    巨门: "In this cycle, words are instruments—investigation, contracts, and public framing move reality. Use “steelman → recommend” memos, write options A/B with a decision date, and keep a repository of precedents. If conversations loop, put it in writing and ask for sign-off. Precision in language now prevents expensive fixes later.",
    天同: "As the decade unfolds, harmony and hospitality become strategy—customer care and community reduce friction and churn. Keep a quarterly friction log; remove the top three annoyances and show the before/after. Guard rest without losing pace by committing to small weekly deliverables. Your signature becomes gracious reliability—people stay because life runs smoother with you.",
    天相: "At this stage of your 10-year cycle, balance and justice are your operating system. Set criteria up front, rule on time, and publish brief post-mortems so decisions feel fair and final. If accommodation drags things out, declare a default path with a deadline. Predictable, transparent process becomes your moat.",
    武曲: "For this chapter, numbers and execution lead. Build a simple scoreboard (inputs you control, outputs you measure) and negotiate on facts, not vibes. Update quickly when data shifts, but keep rapport even when you’re firm. Ship, reconcile, improve, repeat—the cadence is the advantage.",
    天梁: "Presently, you’re protector and mentor—risk management and advocacy earn trust. Define escalation thresholds before crises, document safeguards, and teach the playbook so others act safely. The trap is endless review; set decision deadlines and publish the trade-off. Timed prudence becomes authority.",
    太阳: "This decade favors visibility and mission. Adopt a daily “show up” habit (teach, demo, update) while guarding sleep and scope. Right-size promises, delegate boldly, and keep feedback loops short so your light warms rather than blinds. Consistent public shipping compounds fast.",
    七杀: "In this ten-year stretch, decisive action in competitive arenas is rewarded. Pre-commit safety lines, train for edge cases, and give crisp commands when pressure spikes—teams rally to clear shields. Before burning a bridge, write the alternative plan, then act fast and clean. Courage plus containment wins.",
    天机: "Across the current cycle, strategy-in-motion rules: curiosity, systems thinking, and tiny optimizations stack. Lock into 6-week cycles—hypothesis, three experiments, one review—so restlessness becomes progress. Log learnings, retire what doesn’t work, scale what does. Adaptive design on rails builds momentum.",
    左辅: "Through this chapter, allies and infrastructure amplify you. Build an advisory bench, codify help into checklists, and repay support by sharing playbooks others can use. If you catch yourself waiting for rescue, set an if-then rule: if input isn’t back by Tuesday, choose the best path and proceed. Community plus ownership keeps you moving.",
    右弼: "In this 10-year run, goodwill and diplomacy open doors. Map a relationship cadence (check-ins, collaborations), align incentives early, and convert friendly talks into written next steps. When conversations get too soft, name the trade-off kindly and ask for a commitment. Ease is your edge—turn it into joint wins you can count.",
    文昌: "During the present cycle, disciplined learning and crisp communication are the lever. Build a lightweight knowledge system—capture → connect → create—so insights turn into output. Perfectionism is the saboteur; ship a v1 with a review checklist and iterate on schedule. Exams, documentation, and policy drafts favor you now—let clarity lead action.",
    文曲: "Over this decade, artistry and persuasion do the heavy lifting. Draft a living style guide (voice, imagery, rhythm) and curate rooms—not just posts—so relationships multiply reach. If form starts to outrun substance, anchor every piece to one measurable outcome. Then turn charm into launches, performances, campaigns, or partnerships that can be counted.",
  },
  大兄: {
    紫微: "In the current 10-year cycle, Zi Wei in Da Xiong makes you the natural hub of your peer group—people defer to your judgment and gather around your standards. Treat your circle like a board you chair: set shared goals, define roles, and institute a cadence for decisions. If ego or status contests flare, re-center on outcomes and draft a charter everyone signs. Lead generously, give credit loudly, and your network turns into a stable coalition.",
    破军: "With Po Jun in Da Xiong, this cycle shakes up your circle—old alliances dissolve so better ones can form. Expect friend-group pivots, team restructures, or leaving cliques that cap your growth. Run “small bets” with new collaborators and keep clean exit terms; if a partnership falters twice, part amicably within a week. Courageous pruning creates space for allies who match your next chapter.",
    天府: "Tian Fu here stabilizes your peer ecosystem—trust, resources, and favors flow when you play steward. Think shared tools, pooled budgets, or co-owned assets that make everyone stronger. Institute transparent accounting and a “give first” policy; quarterly, audit who needs support and who can contribute. Beware comfort-drift—pair generosity with targets so the circle compounds value, not inertia.",
    廉贞: "Lian Zhen in Da Xiong turns reputation and boundaries into the glue of your relationships. You’ll thrive in circles that respect clear rules, NDAs, and brand-safe conduct. Convert values into simple agreements, time-box decisions, and decline politely when dynamics feel murky. If politics brew, move the talk to written terms—integrity, documented, keeps friendships intact.",
    太阴: "Tai Yin brings quiet loyalty and behind-the-scenes support: a few good peers are worth a stadium. Schedule low-noise check-ins, share drafts privately, and invest in financial hygiene with accountability buddies. If you start hiding excellent work, agree to a 48-hour “ship a small version” pact. Soft care plus steady compounding turns your friend group into a safety net.",
    贪狼: "Tan Lang colors the cycle with magnetism—your social radius expands fast. Use it, but channel it: pair every social splash (event, collab, drop) with ops and boundaries (budgets, roles, deliverables). Pick rooms that multiply reach and track one metric that proves the network works (referrals, conversions). Charm draws the crowd; structure keeps the right ones close.",
    巨门: "Ju Men makes conversation your power tool: debates, contracts, and public framing define alliances. Practice “steelman → propose” in group threads; publish short memos with Option A/B and a decision date. If talk loops, move to written agreements and minutes. Clean language prevents rumor mills—your clarity becomes the circle’s risk control.",
    天同: "Here, Tian Tong turns your peer group into a quality-of-life engine—hospitality and kindness reduce friction and churn. Keep a quarterly “friction log” for the circle; remove the top three annoyances and celebrate before/after. Guard rest without losing pace by committing to one small shared deliverable weekly. People stay because life gets easier around you.",
    天相: "Tian Xiang in Da Xiong favors fair process and balanced roles—your gift is making collaboration feel just. Set criteria up front, rotate responsibilities, and issue brief post-mortems so calls feel transparent. When accommodation drags, declare a default path with a deadline. Predictable rules plus timely rulings give your circle a durable spine.",
    武曲: "Wu Qu makes the network pragmatic and numbers-led: peers trust you when the math works. Build a simple scoreboard for joint efforts (inputs, outputs, review cadence) and negotiate on facts. Update fast when data shifts, but keep rapport warm. Ship, reconcile, improve, repeat—the cadence turns acquaintances into a high-performing crew.",
    天梁: "With Tian Liang, you become protector and mentor in your circle—people come to you for cover and wisdom. Define escalation thresholds before drama spikes, document safeguards, and teach others to self-protect. The trap is over-review; set decision deadlines and publish trade-offs. Your steady advocacy earns long-term loyalty.",
    太阳: "Tai Yang lights up public collaboration—co-teaching, joint campaigns, and visible service bind the group. Adopt a daily “show up” habit (share, demo, shout-out) while guarding sleep and scope. Right-size promises and delegate boldly so spotlight doesn’t burn people out. Shared visibility becomes shared momentum.",
    七杀: "Qi Sha energizes competitive, high-stakes teamwork—hackathons, crisis response, turnarounds. Pre-commit safety lines, run short ops checklists, and issue crisp commands in crunch moments; clear shields rally peers. Before you torch a bridge, write the alternative plan; then act fast and clean. Courage plus containment turns rivals into battle-tested allies.",
    天机: "Tian Ji here means strategy-in-motion across the network—ideas iterate quickly when you link smart minds. Lock into 6-week cycles (hypothesis → 3 experiments → review), share dashboards, and retire duds publicly. If restlessness scatters focus, pick one thesis per cycle. Adaptive thinking on rails keeps the circle inventive without chaos.",
    左辅: "Zuo Fu highlights helpful allies and sturdy scaffolding. Build an advisory bench, codify help into checklists, and repay support by publishing playbooks others can reuse. If you’re waiting for rescue, set an if-then: if input isn’t back by Tuesday, choose the best path and proceed. Mutual aid plus ownership keeps momentum alive.",
    右弼: "You Bi adds diplomacy and goodwill—intros, referrals, and smooth negotiations flow. Map a relationship cadence (check-ins, co-projects), align incentives early, and turn friendly talks into written next steps. When conversations get too soft, name the trade-off kindly and ask for a commitment. Ease is your edge; convert it into shared wins.",
    文昌: "Wen Chang makes the circle a study club and documentation machine. Create a lightweight knowledge system (capture → connect → create), co-edit templates, and use review checklists to raise the floor for everyone. Perfectionism is the trap; ship v1s on schedule and iterate. Clear writing becomes the network’s compound interest.",
    文曲: "Wen Qu brings artistry and persuasive polish to your peer world—co-writing, branding, music, design. Draft a shared style guide (voice, imagery, rhythm) and curate rooms where taste and results meet. If form starts outrunning substance, anchor each piece to one measurable outcome. Then turn charm into launches, campaigns, and partnerships you can count.",
  },
  大夫: {
    紫微: "In this partnership-focused decade, Zi Wei frames you as a steady leader within the bond—marriage, key clients, or a cofounder. Draft a shared charter, define roles, and practice service-first authority so both voices are honored. When ego spikes, re-center on outcomes and co-own decisions. Lead generously and the relationship compounds trust.",
    破军: "Across the current 10-year cycle, Po Jun resets patterns that don’t serve the two of you. Retire stale loops, prototype new rituals, and close misaligned chapters cleanly. Run small experiments with pre-agreed kill criteria so change feels safe. Bold pivots plus contingency plans restore momentum.",
    天府: "This decade favors dependable bonds and well-run households or partnerships. Build joint reserves, create simple ops (calendar, chores, budgets), and review money quarterly. Reliability becomes affection when promises are kept. Comfort stays healthy when paired with clear growth goals.",
    廉贞: "Right now, boundaries and ethics are the love language. Convert values into written agreements, use NDAs or guardrails for public-facing work, and time-box hard talks. Integrity, demonstrated consistently, becomes attraction. Reputation-safe choices keep the bond strong under pressure.",
    太阴: "Over this 10-year chapter, Tai Yin brings gentle care and quiet strategy to the duo. Design calming spaces and workflows, check in softly, and practice patient finance together. If avoidance appears, ship a small truth kindly within 48 hours. Soft care plus steady habits builds deep safety.",
    贪狼: "During this cycle, desire and social sparkle enrich the pair. Say yes to shared adventures—events, travel, creative projects—but pair them with rules: budget, calendar, boundaries. Pleasure fuels closeness when structure holds. Track one metric (time together, savings, or output) to keep joy sustainable.",
    巨门: "Communication is decisive throughout this decade. Clarify expectations, document decisions, and resolve rumors fast with “steelman → propose” conversations. Put key terms in writing to protect both sides. Clear language prevents small misunderstandings from becoming big problems.",
    天同: "As the decade unfolds, harmony becomes strategy. Build weekly rituals, create polite conflict rules, and celebrate small wins that ease daily life. Protect peace without losing pace by committing to one visible deliverable each week. A peaceful rhythm multiplies affection.",
    天相: "Fairness anchors the current cycle. Set decision criteria together, rotate responsibilities, and close loops on time so neither carries the unseen load. When stuck, declare a default path with a review date. Justice felt becomes love sustained.",
    武曲: "For this chapter, finances and logistics are the bond’s backbone. Build a budget you both believe in, define procurement rules, and track shared KPIs for goals like debt, savings, or launches. Negotiate on facts while keeping tone warm. Practical wins become emotional security.",
    天梁: "Protection and mentorship define the tenor of these years. Create escalation thresholds, safety plans, and teach each other the playbook under stress. Avoid over-review by setting decision deadlines and publishing trade-offs. Reliable advocacy earns long-term loyalty.",
    太阳: "Visibility as a duo rises in this decade—co-present, co-host, or share a public project. Adopt a “show up together” habit while guarding energy and scope. Right-size promises to avoid burnout. Shared spotlight, handled well, strengthens the bond.",
    七杀: "High-stakes moments call for decisive repairs now. Set safety lines, train for edge cases, and act fast in crises with clear roles. Before you torch a bridge, write the alternative plan; then move cleanly. Courage with containment preserves respect and closeness.",
    天机: "Systems and iteration shape the partnership through this cycle. Use shared calendars, a single source-of-truth doc, and 6-week habit sprints. Log learnings and keep what works; retire what doesn’t with no blame. Clever process turns two people into one smooth team.",
    左辅: "Helpful allies appear when you ask—therapists, coaches, wise friends. Accept support and repay by sharing what you learn with others. Document routines so help persists even when people rotate. A supported partnership becomes resilient.",
    右弼: "Diplomacy is your superpower this decade. Curate joint networks, practice soft-power introductions, and turn goodwill into concrete next steps. Name trade-offs kindly and ask for commitments in writing. Friendly doesn’t mean fuzzy—clarity keeps warmth intact.",
    文昌: "Planning and documentation lift the relationship’s baseline. Build shared checklists, a home/ops manual, and quarterly reviews. Perfectionism? Ship v1 plans and iterate on schedule. Clear notes prevent repeat friction.",
    文曲: "Romance and expression color these years. Craft a “house style” for how you celebrate, post, and speak in public; protect intimacy with agreed boundaries. Pair beauty with one measurable outcome—more dates, a finished project, or money saved. Style becomes substance when tracked.",
  },
  大子: {
    紫微: "This decade casts Zi Wei as the benevolent director of creations and the mentor of the young. Treat the studio/classroom as your stage: publish a showcase calendar, set simple milestones, and model standards others can copy. If ego or perfection creeps in, ask which outcome helps the learner or the project most right now—and decide. Mentor two juniors, build a flagship piece, and let leadership be visible but kind.",
    破军: "Through this 10-year arc, Po Jun breaks creative ruts and resets unhelpful patterns with clean cuts. Prototype fast, run pre-mortems, and retire a concept that stalls twice—no zombie projects. Create a greenfield portfolio with clear kill criteria so bold pivots feel safe rather than chaotic. After each cut, build new scaffolding immediately so momentum becomes upgrade, not mess.",
    天府: "Over this chapter, Tian Fu favors durable assets—children’s education funds, IP libraries, instruments, and well-made tools. Set automatic contributions, register rights, and maintain an archive so compounding can work quietly. Reliability and steady practice become the love language of growth. Choose quality you can hold through noise rather than flashy spikes.",
    廉贞: "Right now Lian Zhen turns passion into form—rules, ethics, and brand safety protect the child and the creation. Write simple house guidelines for screens, study, and public posts; get permissions in place for any sharing. Time-box the hard talks and document agreements so heat turns into clarity. Integrity, demonstrated consistently, becomes the magnet that attracts support.",
    太阴: "As this chapter unfolds, Tai Yin nourishes through gentle routines and design that calms effort. Nightly reading, quiet craft, and patient tutoring create safety for growth; build a “safe stage” to show small work without fear. If hesitation appears, ship a modest version within 48 hours and iterate softly. Soft power, repeated, becomes durable confidence.",
    贪狼: "During these years, Tan Lang adds spark—performance, play, and social magnetism gather audiences. Use temptation-bundling: pair the fun thing (stage, event, collab) with the necessary thing (practice, budget, boundaries) so joy stays sustainable. Track one metric—hours practiced, showcases shipped, or savings toward gear—to keep glamour grounded. Say yes to visibility, no to messy entanglements.",
    巨门: "In this period, Ju Men trains articulation: debates, presentations, and the wording of rules shape outcomes. Practice “steelman then propose,” write A/B options with a decision date, and set civility norms for online speech. Because precise language reduces risk, keep decision logs and feedback notes people can cite. Clarity turns noise into skill and rumor into record.",
    天同: "Across the decade, Tian Tong pursues happy rhythms—ease and kindness as strategy. Reduce overscheduling, protect weekends, and anchor two joy-rituals each week that everyone can keep. Celebrate before/after improvements so morale compounds. Peace with progress beats peace that stalls.",
    天相: "For this chapter, Tian Xiang asks for fairness that can be felt and audited. Publish simple rubrics, rotate responsibilities, and close decisions on time so no one carries invisible load. When disputes arise, name the criteria and declare a default path with a review date. Justice practiced becomes motivation sustained.",
    武曲: "Presently Wu Qu makes measurement your coach. Build a friendly scoreboard—practice reps, drafts finished, allowance saved—and review weekly without shaming. Use micro-incentives and celebrate consistency over streaks of perfection. Numbers spoken kindly turn effort into habit.",
    天梁: "With Tian Liang, protection and mentorship frame growth: safe nets let braver steps happen. Create a challenge ladder (level up tasks with clear safeguards), define escalation thresholds, and teach risk basics. Avoid overprotection by setting time-limited experiments with debriefs. Steady advocacy earns trust; trust unlocks effort.",
    太阳: "This decade likes sunlight—showing work, teaching publicly, and proud demos. Host small demo days, post progress, and praise effort over innate talent to prevent burnout. Guard scope and sleep so spotlight warms rather than scorches. Consistent, humble visibility compounds fast.",
    七杀: "Across this span, Qi Sha forges grit through real stakes—competitions, auditions, or tough builds. Pre-commit safety lines and code of conduct so courage never slides into harm. Run short, intense sprints with clear after-action reviews, and cut toxic influences fast and clean. Calm ferocity plus containment becomes confidence.",
    天机: "In this cycle, Tian Ji turns curiosity into systems that scale learning. Build pipelines—ideate → draft → review → publish—and use 6-week sprints with three small experiments each. Spaced repetition and project journals convert insight into output. Restlessness, on rails, becomes progress.",
    左辅: "Zuo Fu assembles the village—tutors, coaches, supportive relatives, peers who lift the work. Ask early, accept help, and repay by documenting routines others can follow. Create feedback loops that outlast any one person so support persists. Community becomes the quiet engine of growth.",
    右弼: "You Bi grows a kind network—clubs, parent groups, creator circles that open doors. Map a cadence for check-ins and collaborations, align incentives early, and turn friendly intent into concrete next steps. When conversations get too soft, name the trade-off kindly and ask for a commitment. Goodwill converted to practice becomes momentum.",
    文昌: "Here Wen Chang upgrades discipline—libraries, notes, and clean templates raise the floor for everyone. Build a lightweight PKM system (capture → connect → create) and ship drafts on schedule with review checklists. Perfectionism is the saboteur; done, then improved, wins. Clear writing becomes compound interest.",
    文曲: "Over this stretch, Wen Qu elevates artistry and voice: portfolios, performances, and design that feels true. Draft a living style guide (tone, imagery, rhythm) and anchor every piece to one measurable outcome—audition, scholarship, launch, or patron. Curate rooms where taste and results meet. Beauty tied to a number travels far.",
  },
  大财: {
    紫微: "This decade puts you in charge of capital strategy—Zi Wei steers allocation with dignity and data. Draft an investment policy statement, set a monthly cashflow council, and delegate thresholds for spend/approve so speed doesn’t kill control. When status temptations appear, ask which move improves free cashflow or strategic moat right now, then decide. Lead calmly, publish the playbook, and let stewardship be your brand.",
    破军: "Po Jun overhauls money systems with clean exits and bold pivots. Close weak products, sell underperforming assets, and rebuild revenue models on simpler rails. Use pre-mortems, stop‑loss rules, and two contingencies per big bet so disruption becomes upgrade, not chaos. Cut decisively; stand up the new pipeline within days so momentum doesn’t leak.",
    天府: "Tian Fu favors quiet compounding—reserves, durable assets, and boring wins that last. Dollar‑cost average, buy quality you can hold, and prioritize cashflow stability over splashy spikes. Run quarterly audits and keep a buffer policy that lets you sleep well. Reliability turns into reputation; reputation discounts your future cost of capital.",
    廉贞: "With Lian Zhen, ethics and brand safety are non‑negotiable in finance. Separate accounts, require dual approvals, and keep audit trails that read like daylight. Decline gray money and time‑box investigations so caution doesn’t stall commerce. Integrity reduces hidden costs and attracts partners who play long games.",
    太阴: "Tai Yin builds wealth softly: patient research, design‑led value, and steady saving habits. Schedule quiet analysis hours, automate contributions, and let time do most of the lifting. If hesitation shows up, execute the smallest compliant buy and review in 30 days. Gentle discipline compounds better than bursts.",
    贪狼: "Tan Lang opens lifestyle and brand revenue—audiences respond to your spark. Pair every splash (launch, event, promo) with ops and budgets (inventory, fulfillment, support) so glamour converts. Track one metric that proves the charm works—conversion, retention, or net revenue—then double down. Joy plus guardrails equals profit.",
    巨门: "Ju Men wins through language: pricing pages, contracts, and clauses that remove ambiguity. Steelman the counterparty’s view, then propose terms A/B with a decision date. Lock SLAs, royalties, and scope in writing; rumor costs more than lawyers. Precision now prevents expensive fixes later.",
    天同: "Tian Tong smooths cashflow by improving customer experience. Keep a refund/complaint log, remove the top three frictions each quarter, and celebrate before/after results. Happy users buy again; retention is revenue you don’t have to chase. Peaceful operations are profitable operations.",
    天相: "Tian Xiang prefers fair, transparent deals made on time. Publish pricing policies and escalation paths; decide when you said you would and document the why. If talks drift, declare a default path with a deadline. Predictable justice attracts repeat business.",
    武曲: "Wu Qu is prime here—numbers, margins, and execution. Build a scoreboard of controllable inputs and measured outputs; negotiate procurement like a pro and prune waste relentlessly. Update when data shifts but keep relationships warm. Ship, reconcile, improve, repeat—the cadence is the edge.",
    天梁: "Tian Liang safeguards the stack: insurance, compliance, and risk controls before scale. Define thresholds, run tabletop drills, and keep backups for people, data, and suppliers. Protection preserves compounding. When in doubt, sandbox first, then roll out.",
    太阳: "Tai Yang grows revenue through outreach—teach to sell, demo to learn, serve to earn. Adopt a public cadence while guarding scope and rest. Right‑size promises and delegate delivery so light warms, not burns. Visibility that ships becomes growth.",
    七杀: "Qi Sha thrives in decisive, high‑stakes moves—turnarounds, distressed buys, or competitive bids. Pre‑commit position sizing and loss limits; when criteria hit, act fast and clean. Do a brief after‑action review and move on. Courage plus containment protects capital.",
    天机: "Tian Ji optimizes funnels and systems. Instrument data end‑to‑end, A/B offers, and run 6‑week cycles: hypothesis → experiments → deploy. Retire duds publicly and scale what works. Small edges stacked monthly become big money yearly.",
    左辅: "Zuo Fu brings backers, sponsors, and friendly capital. Build an update rhythm (monthly memo, quarterly call) and repay support with honest metrics and shared wins. Map who unlocks what and keep promises promptly. Good patrons arrive when you treat the first ones well.",
    右弼: "You Bi multiplies wealth via warm introductions and goodwill. Maintain a simple CRM, nurture referrers, and convert friendly chats into written next steps. When talks get soft, name the trade‑off kindly and ask for a commitment. Diplomacy that closes is a profit center.",
    文昌: "Wen Chang turns finance into a tidy machine: SOPs, reconciliations, and close‑the‑books rituals. Standardize invoices and payouts; write plain‑language summaries for stakeholders. Perfectionism stalls flow—ship v1 processes, then iterate on schedule. Precision prevents leaks.",
    文曲: "Wen Qu monetizes presentation—brand voice, design, and narrative that make value obvious. Draft a style guide for pricing pages, decks, and pitches; tie aesthetics to one number (conversion, ACV, LTV). Beauty that sells is beauty tied to metrics. Polish with purpose.",
  },
  大疾: {
    紫微: "This decade makes you the CEO of your wellbeing. Set standards, assemble a care team (GP, dentist, physio), and run annual reviews like board meetings. If choices feel fuzzy, ask which action most improves energy and longevity right now—then decide. Publish a one‑page personal health ops manual so habits survive busy seasons.",
    破军: "Across this chapter, Po Jun breaks harmful loops with clean cuts. End the substances, late nights, or stress triggers that keep compounding debt; replace each with a simpler routine within 48 hours. Use pre‑mortems and 30‑day resets so bold changes feel safe. Cut decisively, rebuild capacity stepwise, and keep two contingencies for rough weeks.",
    天府: "Steady deposits beat heroic sprints. Sleep, nutrition, and strength practice are your blue‑chip assets; small, automatic contributions pay dividends. Build buffers—meal prep, refill schedules, a “rainy‑day” energy plan—so health holds under stress. Reliability becomes resilience.",
    廉贞: "Boundaries are medicine. Define work‑stop lines, recovery protocols, and privacy settings for health disclosures; document them so they survive pressure. Time‑box hard conversations about workload and hold people (including you) to the rules. Integrity in routines protects reputation and body alike.",
    太阴: "Recovery is a design problem. Optimize sleep hygiene, light, sound, and temperature; create a nightly wind‑down that takes two minutes to start and is hard to skip. Gentle training and quiet practices (breath, stretching, journaling) restore more than they cost. Soft power, repeated, heals.",
    贪狼: "Re‑link pleasure to health. Choose joyful movement, tasty-but-sane meals, and social accountability so discipline feels like desire. Set bright lines for indulgence (budget, frequency) and keep celebrations inside them. When fun has rails, adherence lasts.",
    巨门: "Turn medical complexity into clear choices. Seek second opinions, keep clean records, and translate jargon into a one‑page decision memo with options A/B and dates. Document assumptions and symptoms so future you (and doctors) have signal. Precision in language prevents missteps.",
    天同: "Lower stress by smoothing life. Simplify commitments, protect buffer time, and anchor two micro‑joys daily (walk + music, stretch + tea). A calm baseline makes every protocol easier. Peace with progress beats peace that stalls.",
    天相: "Fairness keeps you well. Balance input and rest, share household or team load transparently, and decide on time so limbo doesn’t drain you. If boundaries slip, publish the criteria and the default plan. Justice, practiced, is healthcare.",
    武曲: "Numbers coach better than nagging. Track a few basics—sleep minutes, steps, protein, training sessions—and review weekly. Update protocols when data shifts, but avoid rigidity that ignores context. Ship, measure, improve—health as operations.",
    天梁: "Protection first. Vaccines, screenings, and risk controls go on the calendar with deadlines; run tabletop drills for emergencies and keep backups for meds and contacts. Mentor others in safety so wisdom multiplies. Prevention preserves compounding.",
    太阳: "Light and service energize. Get outside, move daily, and share what you learn so purpose fuels consistency. Guard scope to avoid “sunburn” burnout—hard stops, honest promises, and real rest. Steady warmth beats brief blaze.",
    七杀: "When stakes rise, act cleanly and fast. Pre‑commit emergency plans and quit‑lines (e.g., for nicotine) so courage has rails. In conflict or crisis, give crisp commands and protect your people—including future you. Courage plus containment heals.",
    天机: "Treat health like an R&D lab. Run 6‑week cycles with hypotheses, a few experiments, and a review; log results and personalize. Retire what doesn’t work without drama. Curiosity on rails becomes progress you can keep.",
    左辅: "Build a bench of helpers—physio, coach, supportive friends. Ask early, accept help, then document routines so support persists when people rotate. Return favors by sharing playbooks. Community is compliance.",
    右弼: "Goodwill is adherence glue. Join classes, find an accountability buddy, and set a gentle check‑in cadence. Name trade‑offs kindly and ask for small commitments. Friendly doesn’t mean fuzzy—write it down.",
    文昌: "Turn care into checklists. Create trackers, prep lists, and plain‑language summaries for clinicians; keep a tidy medical folder. Perfectionism stalls action, so ship v1 routines and iterate on schedule. Documentation lowers friction.",
    文曲: "Make healing environments beautiful. Music, art, scent, and thoughtful design reduce stress and invite consistency. Curate a soothing “recovery kit” you enjoy using. Aesthetics that comfort become adherence.",
  },

  大迁: {
    紫微: "This 10-year chapter casts you as the anchor in motion—people look to you to make travel and expansion feel orderly. Treat geography like a portfolio: pick an anchor base, name two satellite hubs, and publish a cadence (quarterly visits, monthly town halls). Appoint local lieutenants and write a short “how we decide when remote” playbook. Your job is to make systems portable so results don’t depend on being in the room.",
    破军: "A decade for bold moves and clean breaks—new cities, new markets, new identity. Run 90-day landing sprints: minimal kit, clear goals, pre-agreed kill criteria for each location. Sell or store what ties you down, keep a go-bag, and line up two fallback plans per country (visa, banking, workspace). The risk is chaos; counter it with checklists and a weekly reset. Cut what no longer fits, then build lean scaffolding that lets the next chapter move fast.",
    天府: "Stability on the move: logistics, reserves, and comfort that pays for itself. Build multi-currency buffers, duplicate mission-critical gear, and decide “home base vs. serviced stay” by cost and focus. Quarterly, review insurance, taxes, and asset safety across jurisdictions. If comfort drifts into clutter, impose a one-in-one-out rule on gear. Your calm stewardship makes travel sustainable—people trust you because the numbers, and the plans, always close.",
    廉贞: "Reputation management and clean boundaries drive every trip. Convert values into travel rules: what you won’t do, what you always document, and how you negotiate abroad. Standardize NDAs, scopes, and payment terms; time-box decisions so politics don’t sprawl. If a situation turns murky, move it to written terms and escalate by the book. Discipline keeps your brand intact while your map changes—integrity, documented, is portable power.",
    太阴: "Quiet momentum suits you: deep work in transit, patient finances, and intimate circles wherever you land. Block night hours for focused craft, automate savings, and keep gentle rituals (journaling, walks) that make unfamiliar places feel safe. If isolation creeps in, schedule two soft social anchors per week (study group, co-work day). Small, steady habits compound—your low-noise style builds lasting value while the world whirls past.",
    贪狼: "Magnetism meets mileage: conferences, launches, and scenes become opportunity funnels. Pair every splashy night (event, collab, show) with a next-day ops block (invoices, follow-ups, deliverables). Choose rooms that multiply reach, not just fun, and track one hard metric—referrals, conversions, or paid bookings. Boundaries keep charm clean: write a simple “how I work on the road” page and stick to it. Keep the sparkle, add the system.",
    巨门: "Your leverage travels through language—framing, contracts, and the questions nobody else asks. Before each trip, prep a memo: local context, terms, likely objections, your recommendation. In meetings, steelman the other side, then offer Option A/B with a decision date. If talk loops, move to written minutes and sign-offs. Precision prevents rumor mills in unfamiliar terrain; clear words cut translation risk and save money.",
    天同: "Hospitality is your strategy: you reduce friction for peers, partners, and clients wherever you go. Keep a “friction log” (top three annoyances per city) and remove them quarter by quarter. Host low-key gatherings that make strangers feel at home, and commit to one visible weekly deliverable so warmth doesn’t replace output. Your signature becomes gracious reliability—people exhale when you arrive, and they want to work with you again.",
    天相: "Protocol and fairness keep moving parts aligned. Publish criteria before decisions, rotate responsibilities, and issue short post-mortems so calls feel just and final. When accommodation slows progress, declare a default path with a deadline. Prepare letters of support, MoUs, and visa/business docs in a tidy folder for easy reuse. Balanced process is your passport: predictable, documented, and on time.",
    武曲: "Numbers and execution travel well. Cost every trip with a simple ROI sheet (inputs you control, outputs you measure, cadence you keep). Negotiate on facts—benchmarks, quotes, freight rates—then verify. Update plans fast when data shifts, but keep relationships warm even when you’re firm. Ship, reconcile, improve, repeat. Your discipline turns routes into revenue and itineraries into operating plans.",
    天梁: "Guardian energy on the road: risk management, mentorship, and ethical cover. Set escalation thresholds before you fly (health, legal, safety), maintain an ICE document, and carry redundant access to funds and IDs. Teach the playbook so others can protect themselves, too. The trap is over-review; set decision deadlines and publish trade-offs. Timed prudence earns trust—and trust opens doors in new places.",
    太阳: "Fieldwork and evangelism light up this chapter. Plan a public cadence (talks, demos, classes) and a private one (sleep, recovery, prep) so charisma sustains rather than burns out. Share itineraries early to fill rooms, delegate boldly on the road, and tighten feedback loops so each stop gets sharper. Your visibility turns miles into momentum—show up, teach, ship.",
    七杀: "High-stakes mobility: crisis ops, competitive entries, and tough geographies. Do pre-trip threat models, set safety lines, and rehearse exfil plans with your team. In crunch moments, speak briefly and protect visibly—people rally to clear shields. Before you torch a path, write the alternative plan, then move fast and clean. Courage plus containment turns risky routes into defining wins.",
    天机: "Strategy in motion—routing, automation, and 1% optimizations that stack. Lock into 6-week cycles: hypothesis, three experiments (tools, routes, workflows), one review. Automate travel ops (checklists, templates, alerts) and keep a living dashboard of time-zone load, cost, and output. If restlessness scatters focus, freeze one thesis per cycle. Adaptive systems make mobility feel smooth, not frantic.",
    左辅: "Allies are your infrastructure. Build a bench of local fixers, mentors, and vendors, track them in a simple CRM, and pay fast. Repay favors by documenting playbooks others can reuse. If you notice yourself waiting for rescue, set an if-then: if input isn’t back by Tuesday, choose the best path and proceed. Mutual aid plus ownership keeps trips productive and friendships strong.",
    右弼: "Diplomacy and goodwill open doors at customs and in boardrooms. Map a relationship cadence (check-ins, intros, co-projects) and align incentives early; convert friendly chats into written next steps. When conversations get too soft, name the trade-off kindly and ask for a commitment. Your ease with people turns border crossings into beginnings rather than delays.",
    文昌: "Documentation is your engine: visas, proposals, specs, trip reports. Build a lightweight knowledge system—capture → connect → create—so every mile improves the next. Use review checklists to raise quality on the first pass, and publish weekly updates to keep teams synced across time zones. Perfectionism is the trap; ship v1 on schedule and iterate. Clear writing becomes compound interest on the road.",
    文曲: "Style and story travel with you—brand, design, music, or prose that makes people feel. Draft a portable style guide (voice, imagery, rhythm) and curate rooms where taste meets outcomes. Pair beauty with a metric per piece (sign-ups, sales, invites) so form drives substance. If you drift into people-pleasing, anchor the next release to one measurable result. Turn charm into launches, tours, and partnerships you can count.",
  },

  大友: {
    紫微: "This decade places you at the helm of crews and collaborators—people calibrate to your standards, cadence, and calm. Treat the network like an organization you chair: publish a simple charter, define roles with decision rights, and delegate real authority so outcomes don’t bottleneck at you. Institute a monthly council and a quarterly retrospective so course corrections are normal, not dramatic. If status contests flare, re-center on shared outcomes and document the rules of engagement. Lead generously, credit loudly, and develop two deputies so the circle scales beyond your presence.",
    破军: "Across this 10-year arc, Po Jun refreshes your peer ecosystem through clean breaks and bold rebuilds. Exit low-fit ties with warmth and speed, then run 30–90 day trials with new collaborators using clear goals and pre-agreed kill criteria. Replace drama with checklists, success metrics, and scheduled decision points; if a partnership misses signals twice, part amicably within a week. Keep two fallback paths for critical roles so churn doesn’t stall momentum. Courageous pruning creates space for allies who match the next chapter of your work.",
    天府: "Stewardship is your edge: you stabilize the group with dependable ops, pooled resources, and patient leadership. Formalize shared tools, budgets, and benefits that reduce churn, and make reliability visible with transparent accounting and on-time updates. Hold quarterly health checks on morale, workload, and burn risk, then fix the top three structural gaps before chasing new projects. The temptation is comfort-drift—counter it with a floor-and-stretch target each quarter. Predictable care becomes the culture people choose to stay in.",
    廉贞: "Boundaries and ethics are the glue that keeps the ecosystem clean under pressure. Publish a lightweight code of conduct, require written scopes for collaborations, and use NDAs or brand-safety rails when you go public together. Time-box hard conversations and move sensitive negotiations to documented channels so heat becomes clarity. If politics start to swirl, escalate by the book and decide on schedule. Credibility practiced consistently converts into long-term trust and access.",
    太阴: "Quiet care reduces churn: think 1:1 check-ins, thoughtful feedback, and spaces where deep work is normal. Build gentle routines that lower stress for the group—office hours, calm sprint rituals, and shared notes that prevent last-minute scrambles. If tension rises, soften the room first (reflect, summarize, ask), then resolve with clear next steps and a date. Protect rest while still committing to one visible deliverable each week. Subtle support compounding over time becomes retention and loyalty.",
    贪狼: "Your social surface area expands—events, showcases, and launches pull in talent and partners. Pair every splash (party, collab, premiere) with a next-day ops block (follow-ups, contracts, fulfillment) so the sparkle converts. Curate rooms that multiply reach, not just fun, and track one hard metric—referrals, conversions, or signed deals—to keep attention honest. Standardize boundaries so charm stays clean and sustainable. Desire becomes a growth engine when tethered to numbers and timelines.",
    巨门: "Language is the lever that turns peers into a high-performing crew. Clarify roles, SLAs, and decision rights in writing; use the steelman-then-propose pattern to transform debate into action. Publish minutes with Option A/B and a decision date to stop loops and rumor chains. Keep a living repository of precedents so people can self-serve answers. Precision upfront saves cycles, money, and goodwill later.",
    天同: "Hospitality is strategy here—remove friction points so collaboration feels easy and generous. Keep a quarterly “friction log” and fix the top three annoyances (tools, timing, handoffs), celebrating before/after wins so morale compounds. Standardize small comforts and humane pacing without letting deliverables slip. If peace starts to stall progress, commit to one small, visible win every week. People return because life simply runs smoother around you.",
    天相: "Fair process earns trust and keeps speed without chaos. Set criteria up front, rotate responsibilities, and close decisions on time with brief post-mortems everyone can read. When accommodation drags, declare a default path with a deadline and a clear review point. Publish your escalation ladder so disagreements resolve predictably. Balanced rules plus timely rulings give the circle a durable spine.",
    武曲: "Execution and numbers lead; the network levels up when you make outcomes measurable and cadence visible. Build a shared scoreboard of controllable inputs and tracked outputs, and audit spend/procurement with tough but fair negotiations. Update quickly when data shifts, yet maintain rapport and face; relationships are assets. Institute a ship → reconcile → improve rhythm so progress never stalls in discussion. Discipline, repeated, becomes the brand of your crew.",
    天梁: "Mentorship and protection define your value to the circle in this chapter. Establish escalation paths, risk thresholds, and safety drills so the team knows what to do under pressure. Advocate fairly when stakes rise, and teach others how to safeguard themselves so wisdom multiplies. The watch-out is over-review—set decision deadlines and publish the trade-off when you call it. Steady guardianship earns long-term loyalty and better bets.",
    太阳: "Public rallying is a superpower—shout-outs, talks, and visible service energize the group and attract allies. Plan a public cadence (weekly shares) and a private one (prep, rest) so charisma sustains rather than burns. Delegate boldly and keep feedback loops short so each showcase gets sharper. Right-size promises to prevent burnout across the crew. Shared visibility, handled well, becomes shared momentum.",
    七杀: "High-pressure teamwork thrives here—hackathons, crisis response, and competitive bids benefit from your decisive edge. Pre-commit safety lines and command protocols so action has rails; when the moment hits, issue brief orders and protect your people visibly. Debrief fast, log lessons, and reset without blame. Before you burn a bridge, write the alternative plan and decide cleanly. Courage plus containment turns stress into performance instead of collateral damage.",
    天机: "Treat org design as an experiment—systems thinking and tiny optimizations raise the whole crew. Run 6-week cycles (hypothesis → three process tweaks → review) with metrics and owner names so learning compounds. Instrument handoffs and tooling to see where work really slows, then retire duds publicly. One thesis per cycle prevents scatter and fatigue. Curiosity on rails becomes durable throughput.",
    左辅: "Sponsors and helpers appear when asked—and when stewarded well, they stick. Assemble an advisory bench, set a monthly update rhythm, and repay support with honest metrics and shared wins. Document playbooks so help scales beyond individuals and survives rotations. Map who unlocks what, then close the loop fast on commitments. Good allies multiply when you treat the first ones like gold.",
    右弼: "Diplomacy and goodwill open doors that hard power can’t. Maintain a simple relationship cadence (check-ins, intros, co-projects) and align incentives early; convert friendly intent into written next steps. When talk gets soft, kindly name the trade-off and ask for a commitment by date. Keep receipts on promises—gentle, not petty. Ease plus clarity builds coalitions that last.",
    文昌: "Documentation raises the floor for everyone—onboarding packs, SOPs, and clean templates make collaboration fast and repeatable. Create a one-hub wiki, add review checklists, and enforce version control so knowledge doesn’t evaporate in chat. Perfectionism is the saboteur; ship v1s on schedule and improve with cadence. Write plain-language summaries for non-experts to keep alignment wide. Clear writing becomes the network’s compound interest.",
    文曲: "Narrative and design attract the right people and keep them. Craft an employer-brand style guide—voice, imagery, rituals—and showcase stories where beauty ties directly to outcomes (retention, referrals, conversion). Curate rooms where taste meets results so collaborators self-select well. If form begins to outrun substance, anchor every campaign to one measurable result. Polished presence, applied to delivery, becomes a recruiting and deal-making engine.",
  },

  大官: {
    紫微: "This decade crowns you with visible authority in career—people calibrate to your standards, cadence, and calm. Treat the org like a system you steward: publish a clear vision, set quarterly priorities, and delegate real decision rights so outcomes do not bottleneck. Institute a governance rhythm (monthly reviews, quarterly retros) and document how decisions are made. If status contests flare, re-center on measurable results and succession. Develop two deputies, codify culture in a short handbook, and make your leadership scalable beyond your presence.",
    破军: "Across this arc, Po Jun favors decisive turnarounds, restructures, and bold pivots. Close stale lines, spin out what no longer fits, and relaunch on simpler rails. Run premortems, set kill criteria, and communicate changes in plain language so courage does not read as chaos. Keep two contingencies for every major bet and time-box migrations. Cut cleanly, then stand up the new operating model fast so momentum becomes upgrade, not noise.",
    天府: "Stewardship is your edge—career gains come from reliable operations, clean books, and assets that compound. Build reserves, tighten procurement, and publish service-level expectations so teams know what “on time” means. Hold quarterly audits on cost, quality, and risk, fixing the top three structural gaps before adding scope. The seduction is comfort-drift; counter it with floor-and-stretch targets. Predictable delivery becomes the brand that earns promotions.",
    廉贞: "Reputation management and principled conduct are your leverage at scale. Convert values into brief, enforceable policies; use written scopes, approvals, and public ethics lines to keep boundaries crisp. Move sensitive talks to documented channels and decide on schedule so heat becomes clarity. If politics swirl, escalate by the book. Integrity lowers the cost of influence—doors open when people trust you will act the same way in the dark as in the light.",
    太阴: "Quiet strategy wins—patient alliances, thoughtful research, and design that reduces friction. Block deep-work hours, write crisp stakeholder memos, and let results speak without theatrics. Automate routine reporting and protect recovery so creativity doesn’t erode. When hesitation appears, ship a modest version within 48 hours and iterate. Calm craftsmanship, repeated, makes you the person leaders consult before they move.",
    贪狼: "Visibility and business development accelerate your rise, but only when charm sits on top of a P&L. Curate rooms that multiply reach, pair every splash (talk, launch, event) with a next-day ops block (follow-ups, contracts, fulfillment), and track one hard metric—conversion, retention, or revenue. Standardize boundaries so charisma stays clean. Desire becomes a growth engine when tethered to numbers and timelines.",
    巨门: "Language is the lever—board memos, contracts, and public statements define reality. Use “steelman then propose,” offer Option A/B with decision dates, and keep a repository of precedents. Nail pricing pages, terms, and RFP responses with ruthless clarity. If talk loops, move to written minutes and sign-offs. Precision up front prevents rumor and rework, saving cycles and reputation.",
    天同: "Culture is a strategic asset here. Improve experience for customers and staff with small, compounding fixes—better tools, clearer handoffs, humane pacing. Keep a quarterly friction log and remove the top three annoyances, celebrating before/after. Protect rest without losing cadence by committing to one visible weekly ship. People stay, buy again, and refer when life simply runs smoother around you.",
    天相: "Governance and fairness keep scale from tipping into disorder. Publish criteria before decisions, rotate responsibilities, and rule on time with short postmortems. When accommodation drags progress, declare a default path with a deadline. Make escalation ladders public so disagreements resolve predictably. Balanced rules plus timely rulings turn you into the trusted arbiter leadership relies on.",
    武曲: "Numbers and execution lead the promotion case. Build a shared scoreboard of controllable inputs and measured outputs, negotiate procurement hard but fair, and prune waste without drama. Update plans quickly when data shifts, keeping rapport warm even when you are firm. Institutionalize a ship → reconcile → improve cadence. Competence repeated becomes credibility, and credibility becomes rank.",
    天梁: "Mentorship and protection are your power. Define risk thresholds, run tabletop drills, and install backstops for people, data, and cash so the org can dare safely. Advocate fairly when stakes rise and teach the playbook so others can protect themselves. Beware over-review; set decision deadlines and publish the trade-off. Timed prudence earns trust—and trust earns scope.",
    太阳: "Field leadership and evangelism light up this chapter. Plan a public cadence (teaching, demos, roadshows) and a private one (prep, rest) so charisma sustains rather than burns out. Share agendas early to fill rooms, delegate boldly on the road, and tighten feedback loops so each outing gets sharper. Your visibility turns missions into movements—show up, teach, ship.",
    七杀: "High-stakes arenas reward your decisiveness—crisis ops, competitive bids, or transformations. Pre-commit kill criteria and safety lines, then act fast and clean when signals hit. In crunch moments, issue brief commands and protect people visibly; teams rally to clear shields. Debrief quickly and move on. Courage plus containment turns pressure into performance instead of collateral damage.",
    天机: "Treat the org as a living system—strategy in motion, dashboards, and 1% improvements that stack. Run 6-week cycles (hypothesis → three experiments → review), instrument handoffs, and retire duds publicly. Lock one thesis per cycle to prevent scatter. Curiosity on rails raises throughput without burning people out. Systems thinking becomes your quiet superpower.",
    左辅: "Sponsors and patrons appear when asked and updated well. Build an advisory bench, maintain a monthly update rhythm, and repay support with honest metrics and shared wins. Map who unlocks what—budget, distribution, credibility—and close loops fast. Good allies multiply when you treat the first ones like gold.",
    右弼: "Diplomacy and coalition-building open doors that solo force cannot. Keep a relationship cadence (check-ins, intros, co-projects), align incentives early, and convert friendly intent into written next steps. If talk goes soft, kindly name the trade-off and ask for a commitment by date. Ease plus clarity turns cross-functional friction into momentum.",
    文昌: "Analysis and documentation push careers upward. Write clean strategy notes, policies, and minutes that non-experts can act on. Build a one-hub wiki, add review checklists, and version your decisions so knowledge survives turnover. Perfectionism is the saboteur—ship v1s on schedule and iterate. Clarity becomes compound interest for the organization and for you.",
    文曲: "Executive presence is story plus design that moves rooms. Draft a style guide for leadership comms—voice, structure, visuals—and tie each narrative to one measurable outcome (adoption, revenue, satisfaction). Curate presentations where taste meets results, and avoid form without substance by attaching a metric to every big moment. Polished storytelling that ships becomes your promotion engine.",
  },

  大田: {
    紫微: "This decade casts you as the dignified steward of land, spaces, and durable assets—people take cues from your standards and upkeep rhythm. Treat property like an institution: maintain an asset register, publish a yearly maintenance calendar, and set capex rules so upgrades beat patches. Appoint a “space marshal” (even if it’s you) to own inspections, contractor vetting, and punch lists. If scope creeps or prestige projects tempt, ask which move lifts safety, cashflow, or long-term value today—then decide. Lead calmly, document house rules, and let consistent care turn places into reputational capital.",
    破军: "A renovation-and-repurpose chapter: demolish the unusable, exit underperforming assets, and rebuild on simpler, stronger lines. Run projects as 90-day sprints with permits, budgets, and clear kill criteria for overruns; store or sell anything that ties you down. Pre-mortem major works, line up two contingencies per critical trade, and phase the work so the home/base stays livable. The risk is chaos—counter with daily site checklists, photo logs, and non-negotiable safety rails. Cut cleanly, then erect lean scaffolding so the new layout supports the life you actually live.",
    天府: "Consolidation is the edge here—quality holdings, dependable tools, and cashflow that lets you sleep. Favor buy-and-hold over flashy flips; build reserves, service the boring essentials, and track yield versus headache. Create a sinking fund for roofs, HVAC, and appliances, and schedule routine inspections so small fixes never become large bills. Keep leverage conservative and acquisitions simple enough to manage on a rainy day. Reliability becomes reputation, and reputation discounts every future negotiation.",
    廉贞: "Rules and ethics protect value: zoning, permits, HOA/strata covenants, brand-safe conduct in shared spaces. Convert values into crisp house or facility policies, keep approvals in writing, and time-box hard conversations with neighbors or co-owners. When dynamics get murky, move talks to documented channels; if image risk rises, pause usage until terms are clear. The watch-out is control games—enforce fairly, not loudly. Integrity, demonstrated, becomes property armor.",
    太阴: "Make sanctuary your strategy—lighting, acoustics, airflow, and storage that soothe the nervous system. Set gentle evening rituals, design a sleep-first bedroom, and declutter in 30-minute wins so momentum feels kind. Build a quiet work nook and a small “comfort kit” (blankets, teas, playlists) that makes recovery automatic. When hesitation stalls upgrades, ship a modest change within 48 hours and revisit next week. Soft power, repeated, turns rooms into batteries that recharge you.",
    贪狼: "Beauty and hospitality want center stage—hosting, gatherings, and lifestyle upgrades that attract people and opportunity. Pair every aesthetic spend with a boundary and a budget: guest policy, cleanup plan, and a next-day ops block for follow-ups. Curate rooms for flow (arrival → mingle → seating → exit) and track one hard metric—bookings, referrals, or rent uplift—so charm pays for itself. Say yes to sparkle, no to messy entanglements. Desire, disciplined, becomes asset performance.",
    巨门: "Words protect walls: leases, addenda, contractor scopes, and neighbor agreements that leave nothing gray. Steelman the other side’s view, then propose terms A/B with dates; keep minutes and photo evidence for every handover. Read strata minutes and local ordinances before you commit, and translate legalese into a one-page summary anyone can act on. If talk loops, escalate by the book and get signatures. Precision now prevents expensive fixes later.",
    天同: "Comfort engineering reduces churn—appliances that always work, routines that keep the place tidy, and handoffs that don’t squeak. Keep a quarterly friction log for the household or facility; fix the top three annoyances and celebrate before/after. Create humane pacing (quiet hours, buffer days after travel) while still committing to one visible improvement each week. Peace is not passivity—ship small wins that everyone can feel. People stay because life runs smoother around you.",
    天相: "Shared ownership thrives on fairness you can audit. Publish decision rights, cost-sharing rules, and a calendar for reviews; rotate responsibilities and close votes on time with brief post-mortems. When accommodation drags, declare a default path with a deadline and a documented opt-out. Keep a tidy folder of deeds, warranties, and meeting minutes so memory can’t rewrite history. Balanced process is the spine that keeps co-owners friends.",
    武曲: "Treat property like an operating line: maintenance ROI, depreciation schedules, and procurement discipline. Build a simple scoreboard—inputs you control (inspections, service intervals) and outputs you measure (utility costs, vacancy, repair spend). Negotiate hard with contractors, require competitive quotes, and pay fast for quality work. Update plans quickly when data shifts, but protect relationships with clear feedback. Ship, reconcile, improve, repeat—the cadence preserves margins.",
    天梁: "Protection first—insurance, inspections, and emergency playbooks before aesthetics. Set escalation thresholds (smell of gas, water on floor, sparks = immediate shutoff + call), run drills, and keep redundant access to funds, keys, and documents. Vet contractors and insist on permits where required; close hazard tickets by date, not mood. The trap is endless review—decide, fix, document. Prudence on a timer turns risk into resilience.",
    太阳: "Activate spaces outward—events, workshops, a visible studio or a field base that serves people. Publish a public cadence while guarding scope and rest; respect neighbors with clear hours, signage, and clean exits. Delegate setup/teardown so the show doesn’t consume the week, and capture leads so each gathering compounds. Lead from the front, listen in the debrief, and keep promises modest and met. Warm light builds community and brand at once.",
    七杀: "Heavy lifts need crisp command: structural repairs, major moves, tough neighborhoods. Pre-brief permits, buffers, and safety lines; in crunch moments, give short orders and protect crews visibly. Stage work to limit downtime and set a hard stop for scope creep. Before burning a bridge with a vendor, write the alternative plan and execute cleanly. Courage plus containment turns gnarly projects into signature wins.",
    天机: "Optimization pays rent—layout logic, storage systems, smart-home automations, and checklists that save minutes daily. Run 6-week cycles (hypothesis → three tweaks → review): rearrange zones, instrument energy usage, refine cleaning SOPs. Keep one thesis per cycle to prevent scatter. Document changes and measure results so what works becomes the new default. Curiosity on rails turns houses into machines that love you back.",
    左辅: "Pros are your infrastructure—reliable agents, surveyors, cleaners, handypeople, gardeners. Build a vetted bench, store contacts in a simple CRM, and pay on time; good vendors stay when treated like partners. Repay favors with referrals and clear scopes that make their day easier. If you catch yourself waiting for rescue, set an if-then: if no reply by Tuesday, choose the best path and proceed. Help scales when ownership stays with you.",
    右弼: "Goodwill lowers friction—neighbors, building staff, and local officials who want you to succeed. Map a relationship cadence (check-ins, small seasonal gifts, quick fixes when you mess up) and convert friendly talks into written next steps. When conversations get soft, gently name the trade-off and ask for a dated commitment. Join the chat group; be the person who closes loops. Diplomacy turns proximity into privilege.",
    文昌: "Paperwork is profit—warranties, manuals, service logs, and a maintenance calendar in one clean hub. Build a lightweight knowledge system (capture → connect → create): scan receipts, tag assets, and set reminders. Write plain-language SOPs for guests, tenants, or family so the place runs without you narrating. Perfectionism is the saboteur—ship v1 binders and iterate. Documentation keeps money from leaking into confusion.",
    文曲: "Aesthetics as an operating system—palette, materials, and signage that make the space feel intentional and easy to use. Draft a style guide (colors, lighting, textures) and moodboard before you buy; tie beauty to one outcome per room (focus, calm, conversion, rent uplift). Curate art and landscaping that age well, not just trend. If form outruns substance, anchor the next spend to a measurable result. Taste plus targets turns design into value.",
  },

  大福: {
    紫微: "This decade emphasizes inner governance—your values, rituals, and dignity in everyday choices become the wellspring of fortune. Treat your inner life like a small institution: draft a personal creed, define weekly and quarterly reviews, and curate inputs (people, media, spaces) that stabilize mood and conscience. Build two anchor rituals you can keep even on bad days, and measure them lightly so consistency, not intensity, becomes the win. When status anxiety or performative virtue creeps in, ask which action honors the principle you chose for this season and move quietly toward it. Mentor without fanfare, give in ways that do not need applause, and codify what “enough” looks like so ambition never erodes peace. Steadiness, repeated, becomes the reputation that unlocks soft, lasting luck.",
    破军: "Po Jun clears spiritual clutter and resets the field so meaning can breathe again. Map the three habits or ties that drain you most, set 30-day exit plans with replacements, and remove triggers within 48 hours (apps, late-night doom loops, rooms that keep you stuck). Use premortems on new practices so bold cuts feel safe—what might fail, and how will you catch yourself kindly? Close chapters cleanly, tell the truth once, then stop explaining; let your calendar and surroundings reflect the new allegiance. Keep two fallback rituals for rough days so momentum survives dips. After the cuts, rebuild structure immediately, or the vacuum refills with the old.",
    天府: "Quiet abundance is the strategy: reserves of sleep, time, goodwill, and modest giving that compound without theatrics. Treat energy like an endowment—spend the yield, protect the principal; put buffers on your calendar before you grant favors. Automate small, regular generosity (time or money) so care outlives mood, and review quarterly whether giving still aligns with values and capacity. Track only what matters—rest sufficiency, solvency, and ability to keep promises—so comfort doesn’t slide into drift. Favor quality you can hold through stress over flashy bursts you cannot sustain. Reliability becomes grace, and grace attracts support you never had to demand.",
    廉贞: "Lian Zhen aligns ethics with action so peace of mind becomes non-negotiable. Write three hard boundaries and two aspirational standards for this phase, then translate each into a concrete behavior (what you will say yes/no to, and how you will say it). Move sensitive exchanges to written agreements, time-box difficult talks, and escalate by policy rather than impulse when pressure rises. Decline elegant offers that break your rules; integrity costs less than reputation repairs. Keep a short ledger of promises made and dates kept so your memory cannot excuse lapses. Consistency under scrutiny becomes your quiet shield.",
    太阴: "Tai Yin nourishes through softness done on purpose—sleep design, evening wind-downs, and spaces that soothe the nervous system. Create a two-minute nightly ritual that is too small to skip, adjust light and sound so rest is default, and keep a gentle journal that tracks comfort without judgment. Build a cozy corner that signals recovery and hold weekly ‘low-noise’ hours where nothing has to be proven. If hesitation stalls care, ship one tiny act within 48 hours and iterate kindly. Seasonally, review what actually restores you and retire the well-intended rituals that do not. Quiet craft, repeated, becomes durable serenity.",
    贪狼: "For Tan Lang, joy is discipline when placed on rails. Curate festivals, art, food, and gatherings that leave you fuller, not hollow, and pair every celebration with boundaries—budgets, time windows, and next-day acts of service. Use temptation-bundling: combine the fun thing (music, friends, travel) with the good thing (movement, gratitude notes, tidy closures) so pleasure funds virtue. Track one simple metric—recovery, savings for experiences, or meaningful invites closed—to keep sparkle honest. Protect against people-pleasing by naming your no-go zones in advance. Desire, governed, becomes a renewable source of luck.",
    巨门: "Ju Men clarifies belief through precise language so faith can survive scrutiny. Keep a doubt journal, steelman opposing views, and write a one-page creed you revisit each quarter; the test is whether behaviors change, not whether slogans sound nice. Translate values into two visible habits and one line you will not cross even when convenient. In public or online, prefer clarity over heat; when rumors start, answer once in writing and move on. Document reconciliations and amends made so repair becomes a practiced art. Words chosen carefully prevent self-deception and spare you avoidable turmoil.",
    天同: "Contentment is engineered here—less friction, more humane pacing, and rituals that make ordinary days feel kind. Keep a monthly joy audit, remove the top three annoyances, and celebrate before-after improvements so morale compounds. Protect quiet time without letting progress stall by shipping one small kindness or task every single week. Create ‘gentle defaults’—walks, tea, simpler menus—that ask little and give much. When others lean on you, serve without martyrdom by naming limits and offering realistic help. Peace you can feel becomes the moat that keeps cynicism out.",
    天相: "Tian Xiang turns fairness into practical devotion seen by others. Publish criteria before you decide, keep promises on schedule, and treat every volunteer hour or mediation as if the outcome will be audited. When endless accommodation slows the group, declare a default path with a review date so kindness and movement coexist. Align commitments with capacity monthly to avoid moral burnout. Keep notes on decisions and reasons, then share summaries so people feel met, not managed. Justice practiced calmly earns unforced authority.",
    武曲: "Wu Qu treats discipline as mercy toward your future self. Track a few basics—sleep minutes, steps or movement minutes, screens, and spend—and let data coach rather than shame. Use a weekly review to re-budget energy the way you would money, and set floor-and-stretch targets so wins are available on hard weeks. When data changes, update protocols without drama; rigidity is not integrity. Build a simple cadence—show up, reconcile, improve—that survives travel and stress. Competence in the ordinary creates space for the extraordinary.",
    天梁: "Tian Liang sanctifies protection and mentorship—guardrails that let courage feel safe. Set escalation thresholds for health, money, and safety; keep an ICE card and redundant access to essential docs and funds. Offer cover fairly, but also teach the playbook so people can protect themselves when you are not there. Avoid endless review by deciding on schedule and documenting trade-offs. Create boundaries that prevent caretaker fatigue—respite is ethical, not selfish. Timed prudence earns deep, quiet trust.",
    太阳: "Tai Yang channels fortune through warm service and visible encouragement. Plan a public cadence—one useful share per day or week—and a private cadence for prep and rest so generosity endures. Spotlight others by name, keep promises modest and met, and draw clear stop lines so shine does not become burnout. Use feedback loops to learn which acts actually help, then do more of that and less of the rest. When attention swells, convert it into tangible aid rather than performance. Steady light turns missions into communities.",
    七杀: "Qi Sha tempers ferocity into clean, ethical action. Set hard lines with vices and corrosive rooms, write the alternative plan before you cut, and then move fast and tidy. In conflict, speak briefly, protect visibly, and document once so the story does not drift. Run after-action reviews that end with specific repairs, not endless blame. Keep courage attached to containment—safety plans, allies on call, and time-boxed confrontations. Sharp, bounded moves build credibility your soul can live with.",
    天机: "Tian Ji treats meaning like R&D—experiments that turn into sustainable practices. Run 6-week cycles with a single thesis (meditation style, sabbath shape, service project), three small experiments, and a short review; keep what reduces suffering and retire what does not. Instrument stress and ease with light signals rather than heavy trackers. Standardize the wins so they survive busy seasons, and maintain a backlog of next ideas without chasing all at once. Curiosity on rails prevents spiritual scatter. Systems make devotion natural on Tuesday afternoons.",
    左辅: "Zuo Fu calls in allies and guides when invited and stewarded well. Assemble a tiny council—elder, peer, beginner—and share monthly notes on what you tried and learned; ask for one hard truth and one encouragement each time. Repay support with punctual updates, gratitude that names specifics, and playbooks others can reuse. Keep boundaries clear so help does not become dependency. Vary whose wisdom you draw from so perspective stays fresh. Community, tended gently, becomes renewable grace.",
    右弼: "You Bi turns diplomacy into everyday blessing. Map a relationship cadence—check-ins, soft introductions, small collaborations—and convert friendly talk into dated next steps. When conversations go vague, kindly name the trade-off and ask for a clear commitment; warmth with edges builds respect. Keep a simple log of promises you owe and those owed to you, then close loops without nagging. Offer credit freely; it costs little and returns much. Goodwill that ships becomes quiet power.",
    文昌: "Wen Chang makes study a form of prayer and practice the proof. Build a light knowledge system—capture → connect → create—and resist perfectionism by publishing small reflections on a schedule. Translate three ideas you love into behaviors you can count; understanding that never changes action is only entertainment. Keep a reading list with ‘why this now’ notes so learning is pointed. Summarize in plain language so others can use what you found. Clarity written down becomes character over time.",
    文曲: "Wen Qu carries virtue on a beautiful signal—style that soothes, words that reconcile, and design that invites rest. Draft a life style guide (tone, colors, music) and curate spaces or messages that dial down noise while pointing toward good. Pair every aesthetic choice with one outcome—comfort offered, bridge built, truth named, generosity sparked—so form serves substance. When people-pleasing appears, return to the metric: did this help someone breathe easier or act better? Archive what merely dazzles. Beauty tied to compassion lingers after you leave.",
  },

  大父: {
    紫微: "This decade places you at the dignified center of lineage—standards, calm judgment, and continuity flow through you. Treat family like a small institution: draft a simple charter (values, conflict rules, giving priorities), set a quarterly elders’ review, and delegate clear roles so decisions don’t bottleneck at one person. Build an archive—photos, deeds, stories—with a naming system and two trusted custodians. When status contests arise, refocus on shared outcomes (health, safety, solvency, harmony) and decide on schedule. Mentor two younger relatives to carry rituals forward and codify what “respect” means in deeds (on-time calls, attendance, budgets). Leadership here is quiet, written, and repeatable.",
    破军: "Po Jun resets family patterns with clean, compassionate breaks. Identify the three loops that corrode trust—gossip, last-minute money panics, unclear caregiving—and dissolve them with new rules and timelines. Retire heirloom obligations that no longer fit, shutter stale committees, and rebuild on simpler rails (one coordinator, one channel, one calendar). Use premortems before big changes, keep two contingencies for care or housing, and close chapters cleanly so the story stops spiraling. After each cut, install scaffolding immediately—checklists, guardianship alternates, shared folders—so momentum becomes repair, not chaos.",
    天府: "Stewardship is the edge: consolidate archives, maintain assets, and build buffers that let elders live with dignity. Create a parents’ fund with a floor (non-negotiable monthly support) and a stretch target (medical, respite, travel), review it quarterly, and keep accounting transparent. Service the boring essentials—insurance, utilities, repairs—before new purchases, and favor quality that lasts over show. Track yield versus headache for every asset and simplify where possible. Reliability becomes love in practice; people sleep because your systems do not.",
    廉贞: "Boundaries and propriety protect the family name and your sanity. Convert values into clear conduct rules—privacy, consent for sharing photos, respectful speech, no surprises with money—and put sensitive matters in writing. Time-box hard talks, escalate by agreed policy rather than impulse, and keep records so memory cannot rewrite history. Decline elegant invitations that break your rules; integrity costs less than repairs after a breach. Consistency under scrutiny becomes your quiet armor.",
    太阴: "Tai Yin anchors gentle caregiving: low-noise routines, restful spaces, and kindness that doesn’t advertise itself. Design a soothing home base—lighting, sound, storage—so care feels safe, not clinical. Create two-minute rituals you can keep on the hardest days (evening tea, brief check-in, gratitude note). If avoidance appears, ship a small kindness within 48 hours and iterate softly. Protect the caregiver with scheduled respite; a calm carer is competent care. Soft power, repeated, becomes durable comfort.",
    贪狼: "Joy is glue when placed on rails—reunions, birthdays, pilgrimages, shared meals that make memory. Curate gatherings that leave people fuller, not drained: set budgets, timelines, and cleanup plans, then pair every party with a next-day ops block (thanks, photos, expenses). Track one metric—attendance continuity, cross-branch participation, or funds raised—so sparkle pays for itself. Set bright lines to prevent people-pleasing from becoming burnout. Desire, governed, turns into family vitality.",
    巨门: "Words keep peace when rooms get crowded. Translate complexity into clear choices: wills, advance directives, care scopes, and household rules written in plain language. In disputes, steelman each side, then propose Option A/B with a decision date; publish minutes so rumors have nowhere to live. Build a story bank—origins, migrations, sacrifices—so identity comes from truth, not whispers. Precision in language prevents preventable hurt and expensive fixes later.",
    天同: "Engineer contentment: fewer frictions, kinder pacing, and rituals that make ordinary days livable. Keep a monthly friction log (top three annoyances in care, chores, communications) and remove them one by one, celebrating before/after. Protect quiet blocks without letting life stall by shipping one visible improvement each week. Name limits kindly to prevent martyrdom and resentment. Peace you can feel is the moat that keeps cynicism out.",
    天相: "Fairness is devotion in public—process that feels just and moves on time. Publish decision criteria before votes, rotate responsibilities, and share short post-mortems explaining why a call was made. When endless accommodation slows progress, declare a default path with a review date. Balance contributions transparently—money, time, logistics—so no one carries invisible load. Predictable justice turns relatives into allies instead of rivals.",
    武曲: "Treat family operations like a budgeted program: inputs you control, outputs you measure, cadence you keep. Build a simple scoreboard—care hours covered, bills paid on time, maintenance closed—and review weekly without shaming. Negotiate procurement firmly (quotes, warranties), pay fast for quality, and prune waste. Update plans quickly when data shifts but keep rapport warm. Ship, reconcile, improve, repeat—the rhythm preserves margins and moods.",
    天梁: "Guardian energy is strongest here—risk management, advocacy, and mentorship that make everyone safer. Set escalation thresholds (health, legal, money), keep an ICE packet (contacts, meds, directives), and run tabletop drills for real crises. Teach the playbook so protection doesn’t depend on one person. Avoid over-review by deciding on schedule and publishing trade-offs. Timed prudence earns deep, quiet trust.",
    太阳: "Lead from the front with warm visibility—ceremonies, community ties, public service in the family name. Plan a public cadence (acknowledgments, memorials, scholarships) and a private one (prep, rest) so generosity sustains. Lift others by name, keep promises modest and met, and draw clear stop lines to avoid burnout. Use feedback to learn what actually helps; do more of that and less of the rest. Consistent light turns lineage into community.",
    七杀: "When it gets hard, move fast and clean. Pre-commit safety lines, guardianship alternates, and hospital/legal go-bags; in crisis, give brief commands and protect visibly so people rally. Before severing a toxic pattern or vendor, write the alternative plan—then act without drama. Hold short after-action reviews that end with specific repairs, not blame. Courage with containment turns pressure into credibility your elders can lean on.",
    天机: "Systems thinking turns love into logistics. Run 6-week cycles—hypothesis (better meds routine, visit rotation), three small experiments, and a review—then standardize wins. Instrument calendars, contacts, and records in one shared hub; color-code duties so gaps show early. Keep one thesis per cycle to prevent scatter and fatigue. Curiosity on rails makes care sustainable on ordinary Tuesdays.",
    左辅: "Allies are infrastructure: social workers, nurses, lawyers, reliable drivers, neighbors who know the spare key. Build a vetted bench, store it in a simple CRM, and pay or thank on time. Ask early, accept help, and repay with clear scopes and tidy follow-ups so people want to help again. Rotate sources to avoid dependency on a single hero. Community, stewarded well, multiplies your reach.",
    右弼: "Diplomacy oils the hinges of the household. Map a relationship cadence—check-ins, soft introductions, small collaborations—and convert friendly talk into dated next steps. When conversations go vague, kindly name the trade-off and ask for a clear commitment. Keep receipts on promises made and owed, then close loops without nagging. Warmth with edges builds coalitions that last through difficult seasons.",
    文昌: "Documentation is devotion made legible. Create a family handbook—contacts, meds, passwords, warranties, rituals—with versioning and access rules. Scan and tag archives; write plain-language summaries for non-experts so anyone can act in a pinch. Perfectionism is the saboteur—ship v1 binders and iterate on schedule. Clear notes prevent repeated pain and keep money from leaking into confusion.",
    文曲: "Wen Qu carries legacy on a beautiful signal—oral histories, letters, albums, and memorials that heal while they honor. Draft a style guide for remembrance (tone, imagery, music), record elders’ stories with consent, and curate exhibitions that tie beauty to outcomes (reconciliation, scholarships, family reunions). Avoid people-pleasing by anchoring each piece to one measurable act of care. When aesthetics serve compassion, memory becomes medicine.",
  },
};
